package com.artur114.bananalib.math.m2d.vec;

import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.m2d.box.IBox2D;
import com.artur114.bananalib.math.m2d.box.IBox2I;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3DM;
import com.artur114.bananalib.math.m3d.vec.IVec3I;

public interface IVec2D extends IVec2DC {
    IVec2D yx();
    IVec3D xyz(double z);
    IVec3D xzy(double z);
    IVec3D zxy(double z);
    IVec3D yxz(double z);
    IVec3D yzx(double z);
    IVec3D zyx(double z);
    IVec2DM yx(IVec2DM out);
    IVec3DM xyz(IVec3DM out, double z);
    IVec3DM xzy(IVec3DM out, double z);
    IVec3DM zxy(IVec3DM out, double z);
    IVec3DM yxz(IVec3DM out, double z);
    IVec3DM yzx(IVec3DM out, double z);
    IVec3DM zyx(IVec3DM out, double z);
    double dot(IVec2IC vec);
    double dot(IVec2DC vec);
    double cross(IVec2IC vec);
    double cross(IVec2DC vec);
    double distance(IVec2IC vec);
    double distance(IVec2DC vec);
    double distanceSq(IVec2IC vec);
    double distanceSq(IVec2DC vec);
    IVec2D add(int x, int y);
    IVec2D add(double x, double y);
    IVec2D add(IVec2IC vec);
    IVec2D add(IVec2DC vec);
    IVec2D subtract(int x, int y);
    IVec2D subtract(double x, double y);
    IVec2D subtract(IVec2IC vec);
    IVec2D subtract(IVec2DC vec);
    IVec2D scale(int val);
    IVec2D scale(int x, int y);
    IVec2D scale(double val);
    IVec2D scale(double x, double y);
    IVec2D scale(IVec2IC vec);
    IVec2D scale(IVec2DC vec);
    IVec2D divide(int val);
    IVec2D divide(int x, int y);
    IVec2D divide(double val);
    IVec2D divide(double x, double y);
    IVec2D divide(IVec2IC vec);
    IVec2D divide(IVec2DC vec);
    IVec2D rotate(double degrees);
    IVec2D rotateAround(int x, int y, double degrees);
    IVec2D rotateAround(double x, double y, double degrees);
    IVec2D rotateAround(IVec2IC point, double degrees);
    IVec2D rotateAround(IVec2DC point, double degrees);
    IVec2D lerp(int x, int y, double delta);
    IVec2D lerp(double x, double y, double delta);
    IVec2D lerp(IVec2IC vec, double delta);
    IVec2D lerp(IVec2DC vec, double delta);
    IVec2D wrap(IBox2I box);
    IVec2D wrap(IBox2D box);
    IVec2D wrap(int x, int y);
    IVec2D wrap(double x, double y);
    IVec2D wrap(int minX, int minY, int maxX, int maxY);
    IVec2D wrap(double minX, double minY, double maxX, double maxY);
    IVec2D clamp(IBox2I box);
    IVec2D clamp(IBox2D box);
    IVec2D clamp(int x, int y);
    IVec2D clamp(double x, double y);
    IVec2D clamp(int minX, int minY, int maxX, int maxY);
    IVec2D clamp(double minX, double minY, double maxX, double maxY);
    IVec2D normalize();
    IVec2DM toMutable();
    IVec2D toImmutable();
    IVec2I floor();
    IVec2I round();
    IVec2I ceil();
    IVec2D copy();
}
