package com.artur114.bananalib.math.m2d.vec;

import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.m2d.box.IBox2D;
import com.artur114.bananalib.math.m2d.box.IBox2I;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3DM;
import com.artur114.bananalib.math.m3d.vec.IVec3I;
import com.artur114.bananalib.math.m3d.vec.IVec3IM;

public interface IVec2I extends IVec2IC {
    IVec2I yx();
    IVec3I xyz(int z);
    IVec3I xzy(int z);
    IVec3I zxy(int z);
    IVec3I yxz(int z);
    IVec3I yzx(int z);
    IVec3I zyx(int z);
    IVec2IM yx(IVec2IM out);
    IVec3IM xyz(IVec3IM out, int z);
    IVec3IM xzy(IVec3IM out, int z);
    IVec3IM zxy(IVec3IM out, int z);
    IVec3IM yxz(IVec3IM out, int z);
    IVec3IM yzx(IVec3IM out, int z);
    IVec3IM zyx(IVec3IM out, int z);
    int dot(IVec2IC vec);
    double dot(IVec2DC vec);
    int cross(IVec2IC vec);
    double cross(IVec2DC vec);
    float distance(IVec2IC vec);
    double distance(IVec2DC vec);
    float distanceSq(IVec2IC vec);
    double distanceSq(IVec2DC vec);
    IVec2I add(int x, int y);
    IVec2I add(double x, double y);
    IVec2I add(IVec2IC vec);
    IVec2I add(IVec2DC vec);
    IVec2I subtract(int x, int y);
    IVec2I subtract(double x, double y);
    IVec2I subtract(IVec2IC vec);
    IVec2I subtract(IVec2DC vec);
    IVec2I scale(int val);
    IVec2I scale(int x, int y);
    IVec2I scale(double val);
    IVec2I scale(double x, double y);
    IVec2I scale(IVec2IC vec);
    IVec2I scale(IVec2DC vec);
    IVec2I divide(int val);
    IVec2I divide(int x, int y);
    IVec2I divide(double val);
    IVec2I divide(double x, double y);
    IVec2I divide(IVec2IC vec);
    IVec2I divide(IVec2DC vec);
    IVec2I rotate(double degrees);
    IVec2I rotateAround(int x, int y, double degrees);
    IVec2I rotateAround(double x, double y, double degrees);
    IVec2I rotateAround(IVec2DC point, double degrees);
    IVec2I rotateAround(IVec2IC point, double degrees);
    IVec2I lerp(int x, int y, double delta);
    IVec2I lerp(double x, double y, double delta);
    IVec2I lerp(IVec2IC vec, double delta);
    IVec2I lerp(IVec2DC vec, double delta);
    IVec2I wrap(IBox2I box);
    IVec2I wrap(IBox2D box);
    IVec2I wrap(int x, int y);
    IVec2I wrap(double x, double y);
    IVec2I wrap(int minX, int minY, int maxX, int maxY);
    IVec2I wrap(double minX, double minY, double maxX, double maxY);
    IVec2I clamp(IBox2I box);
    IVec2I clamp(IBox2D box);
    IVec2I clamp(int x, int y);
    IVec2I clamp(double x, double y);
    IVec2I clamp(int minX, int minY, int maxX, int maxY);
    IVec2I clamp(double minX, double minY, double maxX, double maxY);
    IVec2D normalize();
    IVec2IM toMutable();
    IVec2I toImmutable();
    IVec2D toDouble();
    IVec2I copy();
}
