package com.artur114.bananalib.math.m3d.matrix;

import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.matrix.IMatrix3DC;
import com.artur114.bananalib.math.core.m3d.matrix.IMatrix3FC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2DM;
import com.artur114.bananalib.math.m2d.vec.IVec2I;
import com.artur114.bananalib.math.m2d.vec.IVec2IM;
import com.artur114.bananalib.math.m3d.box.IBox3D;
import com.artur114.bananalib.math.m3d.box.IBox3DM;
import com.artur114.bananalib.math.m3d.box.IBox3I;
import com.artur114.bananalib.math.m3d.box.IBox3IM;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3DM;
import com.artur114.bananalib.math.m3d.vec.IVec3I;
import com.artur114.bananalib.math.m3d.vec.IVec3IM;
import org.jetbrains.annotations.Contract;

public interface IMatrix3D extends IMatrix3DC {
    @Contract("-> new")
    IMatrix3D invert();
    @Contract("-> new")
    IMatrix3D transpose();
    IMatrix3D mul(IMatrix3DC matrix);
    IMatrix3D mul(IMatrix3FC matrix);
    IMatrix3D mulPost(IMatrix3DC matrix);
    IMatrix3D mulPost(IMatrix3FC matrix);
    IMatrix3D div(int val);
    IMatrix3D div(double val);
    IMatrix3D scale(int val);
    IMatrix3D scale(double val);
    IMatrix3D scale(int x, int y, int z);
    IMatrix3D scale(double x, double y, double z);
    IMatrix3D scale(IVec3DC vec);
    IMatrix3D scale(IVec3IC vec);
    IMatrix3D scale(IVec2IC vec, int z);
    IMatrix3D scale(IVec2IC vec, double z);
    IMatrix3D scale(IVec2DC vec, int z);
    IMatrix3D scale(IVec2DC vec, double z);
    IMatrix3D scale(IVec2IC vec);
    IMatrix3D scale(IVec2DC vec);
    IMatrix3D translate(int x, int y, int z);
    IMatrix3D translate(double x, double y, double z);
    IMatrix3D translate(IVec3DC vec);
    IMatrix3D translate(IVec3IC vec);
    IMatrix3D translate(IVec2IC vec, int z);
    IMatrix3D translate(IVec2IC vec, double z);
    IMatrix3D translate(IVec2DC vec, int z);
    IMatrix3D translate(IVec2DC vec, double z);
    IMatrix3D translate(IVec2IC vec);
    IMatrix3D translate(IVec2DC vec);
    IMatrix3D rotateX(double degrees);
    IMatrix3D rotateY(double degrees);
    IMatrix3D rotateZ(double degrees);
    IMatrix3D rotate(double degrees, int x, int y, int z);
    IMatrix3D rotate(double degrees, double x, double y, double z);
    IMatrix3D rotate(double degrees, IVec3DC vec);
    IMatrix3D rotate(double degrees, IVec3IC vec);
    IMatrix3D rotate(double degrees, IVec2IC vec, int z);
    IMatrix3D rotate(double degrees, IVec2IC vec, double z);
    IMatrix3D rotate(double degrees, IVec2DC vec, int z);
    IMatrix3D rotate(double degrees, IVec2DC vec, double z);
    IMatrix3D rotate(double degrees, IVec2IC vec);
    IMatrix3D rotate(double degrees, IVec2DC vec);
    IMatrix3D rotateXAround(int x, int y, int z, double degrees);
    IMatrix3D rotateXAround(double x, double y, double z, double degrees);
    IMatrix3D rotateXAround(IVec3IC point, double degrees);
    IMatrix3D rotateXAround(IVec3DC point, double degrees);
    IMatrix3D rotateXAround(IVec2IC vec, int z, double degrees);
    IMatrix3D rotateXAround(IVec2IC vec, double z, double degrees);
    IMatrix3D rotateXAround(IVec2DC vec, int z, double degrees);
    IMatrix3D rotateXAround(IVec2DC vec, double z, double degrees);
    IMatrix3D rotateXAround(IVec2IC vec, double degrees);
    IMatrix3D rotateXAround(IVec2DC vec, double degrees);
    IMatrix3D rotateYAround(int x, int y, int z, double degrees);
    IMatrix3D rotateYAround(double x, double y, double z, double degrees);
    IMatrix3D rotateYAround(IVec3IC point, double degrees);
    IMatrix3D rotateYAround(IVec3DC point, double degrees);
    IMatrix3D rotateYAround(IVec2IC vec, int z, double degrees);
    IMatrix3D rotateYAround(IVec2IC vec, double z, double degrees);
    IMatrix3D rotateYAround(IVec2DC vec, int z, double degrees);
    IMatrix3D rotateYAround(IVec2DC vec, double z, double degrees);
    IMatrix3D rotateYAround(IVec2IC vec, double degrees);
    IMatrix3D rotateYAround(IVec2DC vec, double degrees);
    IMatrix3D rotateZAround(int x, int y, int z, double degrees);
    IMatrix3D rotateZAround(double x, double y, double z, double degrees);
    IMatrix3D rotateZAround(IVec3IC point, double degrees);
    IMatrix3D rotateZAround(IVec3DC point, double degrees);
    IMatrix3D rotateZAround(IVec2IC vec, int z, double degrees);
    IMatrix3D rotateZAround(IVec2IC vec, double z, double degrees);
    IMatrix3D rotateZAround(IVec2DC vec, int z, double degrees);
    IMatrix3D rotateZAround(IVec2DC vec, double z, double degrees);
    IMatrix3D rotateZAround(IVec2IC vec, double degrees);
    IMatrix3D rotateZAround(IVec2DC vec, double degrees);
    IMatrix3D rotateAround(IVec3DC point, double degrees, int x, int y, int z);
    IMatrix3D rotateAround(IVec3DC point, double degrees, double x, double y, double z);
    IMatrix3D rotateAround(IVec3DC point, double degrees, IVec3DC vec);
    IMatrix3D rotateAround(IVec3DC point, double degrees, IVec3IC vec);
    IMatrix3D rotateAround(IVec3DC point, double degrees, IVec2IC vec, int z);
    IMatrix3D rotateAround(IVec3DC point, double degrees, IVec2IC vec, double z);
    IMatrix3D rotateAround(IVec3DC point, double degrees, IVec2DC vec, int z);
    IMatrix3D rotateAround(IVec3DC point, double degrees, IVec2DC vec, double z);
    IMatrix3D rotateAround(IVec3DC point, double degrees, IVec2IC vec);
    IMatrix3D rotateAround(IVec3DC point, double degrees, IVec2DC vec);
    IMatrix3D rotateAround(IVec3IC point, double degrees, int x, int y, int z);
    IMatrix3D rotateAround(IVec3IC point, double degrees, double x, double y, double z);
    IMatrix3D rotateAround(IVec3IC point, double degrees, IVec3DC vec);
    IMatrix3D rotateAround(IVec3IC point, double degrees, IVec3IC vec);
    IMatrix3D rotateAround(IVec3IC point, double degrees, IVec2IC vec, int z);
    IMatrix3D rotateAround(IVec3IC point, double degrees, IVec2IC vec, double z);
    IMatrix3D rotateAround(IVec3IC point, double degrees, IVec2DC vec, int z);
    IMatrix3D rotateAround(IVec3IC point, double degrees, IVec2DC vec, double z);
    IMatrix3D rotateAround(IVec3IC point, double degrees, IVec2IC vec);
    IMatrix3D rotateAround(IVec3IC point, double degrees, IVec2DC vec);
    IMatrix3D localScale(int val);
    IMatrix3D localScale(double val);
    IMatrix3D localScale(int x, int y, int z);
    IMatrix3D localScale(double x, double y, double z);
    IMatrix3D localScale(IVec3DC vec);
    IMatrix3D localScale(IVec3IC vec);
    IMatrix3D localScale(IVec2IC vec, int z);
    IMatrix3D localScale(IVec2IC vec, double z);
    IMatrix3D localScale(IVec2DC vec, int z);
    IMatrix3D localScale(IVec2DC vec, double z);
    IMatrix3D localScale(IVec2IC vec);
    IMatrix3D localScale(IVec2DC vec);
    IMatrix3D localTranslate(int x, int y, int z);
    IMatrix3D localTranslate(double x, double y, double z);
    IMatrix3D localTranslate(IVec3DC vec);
    IMatrix3D localTranslate(IVec3IC vec);
    IMatrix3D localTranslate(IVec2IC vec, int z);
    IMatrix3D localTranslate(IVec2IC vec, double z);
    IMatrix3D localTranslate(IVec2DC vec, int z);
    IMatrix3D localTranslate(IVec2DC vec, double z);
    IMatrix3D localTranslate(IVec2IC vec);
    IMatrix3D localTranslate(IVec2DC vec);
    IMatrix3D localRotateX(double degrees);
    IMatrix3D localRotateY(double degrees);
    IMatrix3D localRotateZ(double degrees);
    IMatrix3D localRotate(double degrees, int x, int y, int z);
    IMatrix3D localRotate(double degrees, double x, double y, double z);
    IMatrix3D localRotate(double degrees, IVec3DC vec);
    IMatrix3D localRotate(double degrees, IVec3IC vec);
    IMatrix3D localRotate(double degrees, IVec2IC vec, int z);
    IMatrix3D localRotate(double degrees, IVec2IC vec, double z);
    IMatrix3D localRotate(double degrees, IVec2DC vec, int z);
    IMatrix3D localRotate(double degrees, IVec2DC vec, double z);
    IMatrix3D localRotate(double degrees, IVec2IC vec);
    IMatrix3D localRotate(double degrees, IVec2DC vec);
    IMatrix3D localRotateXAround(int x, int y, int z, double degrees);
    IMatrix3D localRotateXAround(double x, double y, double z, double degrees);
    IMatrix3D localRotateXAround(IVec3IC point, double degrees);
    IMatrix3D localRotateXAround(IVec3DC point, double degrees);
    IMatrix3D localRotateXAround(IVec2IC vec, int z, double degrees);
    IMatrix3D localRotateXAround(IVec2IC vec, double z, double degrees);
    IMatrix3D localRotateXAround(IVec2DC vec, int z, double degrees);
    IMatrix3D localRotateXAround(IVec2DC vec, double z, double degrees);
    IMatrix3D localRotateXAround(IVec2IC vec, double degrees);
    IMatrix3D localRotateXAround(IVec2DC vec, double degrees);
    IMatrix3D localRotateYAround(int x, int y, int z, double degrees);
    IMatrix3D localRotateYAround(double x, double y, double z, double degrees);
    IMatrix3D localRotateYAround(IVec3IC point, double degrees);
    IMatrix3D localRotateYAround(IVec3DC point, double degrees);
    IMatrix3D localRotateYAround(IVec2IC vec, int z, double degrees);
    IMatrix3D localRotateYAround(IVec2IC vec, double z, double degrees);
    IMatrix3D localRotateYAround(IVec2DC vec, int z, double degrees);
    IMatrix3D localRotateYAround(IVec2DC vec, double z, double degrees);
    IMatrix3D localRotateYAround(IVec2IC vec, double degrees);
    IMatrix3D localRotateYAround(IVec2DC vec, double degrees);
    IMatrix3D localRotateZAround(int x, int y, int z, double degrees);
    IMatrix3D localRotateZAround(double x, double y, double z, double degrees);
    IMatrix3D localRotateZAround(IVec3IC point, double degrees);
    IMatrix3D localRotateZAround(IVec3DC point, double degrees);
    IMatrix3D localRotateZAround(IVec2IC vec, int z, double degrees);
    IMatrix3D localRotateZAround(IVec2IC vec, double z, double degrees);
    IMatrix3D localRotateZAround(IVec2DC vec, int z, double degrees);
    IMatrix3D localRotateZAround(IVec2DC vec, double z, double degrees);
    IMatrix3D localRotateZAround(IVec2IC vec, double degrees);
    IMatrix3D localRotateZAround(IVec2DC vec, double degrees);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, int x, int y, int z);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, double x, double y, double z);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, IVec3DC vec);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, IVec3IC vec);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, IVec2IC vec, int z);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, IVec2IC vec, double z);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, IVec2DC vec, int z);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, IVec2DC vec, double z);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, IVec2IC vec);
    IMatrix3D localRotateAround(IVec3DC point, double degrees, IVec2DC vec);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, int x, int y, int z);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, double x, double y, double z);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, IVec3DC vec);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, IVec3IC vec);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, IVec2IC vec, int z);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, IVec2IC vec, double z);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, IVec2DC vec, int z);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, IVec2DC vec, double z);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, IVec2IC vec);
    IMatrix3D localRotateAround(IVec3IC point, double degrees, IVec2DC vec);
    @Contract("_,_ -> new") IVec2I transform(int x, int y);
    @Contract("_,_ -> new") IVec2D transform(double x, double y);
    @Contract("_,_,_ -> new") IVec3I transform(int x, int y, int z);
    @Contract("_,_,_ -> new") IVec3D transform(double x, double y, double z);
    @Contract("_ -> new") IVec3I transform(IVec3IC vec);
    @Contract("_ -> _") IVec3IM transform(IVec3IM vec);
    @Contract("_ -> new") IVec3D transform(IVec3DC vec);
    @Contract("_ -> _") IVec3DM transform(IVec3DM vec);
    @Contract("_ -> new") IVec3I[] transform(IVec3IC... vec);
    @Contract("_ -> _") IVec3IM[] transform(IVec3IM... vec);
    @Contract("_ -> new") IVec3D[] transform(IVec3DC... vec);
    @Contract("_ -> _") IVec3DM[] transform(IVec3DM... vec);
    @Contract("_ -> new") IVec2I transform(IVec2IC vec);
    @Contract("_ -> _") IVec2IM transform(IVec2IM vec);
    @Contract("_ -> new") IVec2D transform(IVec2DC vec);
    @Contract("_ -> _") IVec2DM transform(IVec2DM vec);
    @Contract("_,_ -> new") IVec3I transform(IVec2IC vec, int z);
    @Contract("_,_ -> new") IVec3D transform(IVec2IC vec, double z);
    @Contract("_,_ -> new") IVec3D transform(IVec2DC vec, int z);
    @Contract("_,_ -> new") IVec3D transform(IVec2DC vec, double z);
    @Contract("_ -> new") IVec2I[] transform(IVec2IC... vec);
    @Contract("_ -> _") IVec2IM[] transform(IVec2IM... vec);
    @Contract("_ -> new") IVec2D[] transform(IVec2DC... vec);
    @Contract("_ -> _") IVec2DM[] transform(IVec2DM... vec);
    @Contract("_ -> new") IBox3I transform(IBox3IC box);
    @Contract("_ -> _") IBox3IM transform(IBox3IM box);
    @Contract("_ -> new") IBox3D transform(IBox3DC box);
    @Contract("_ -> _") IBox3DM transform(IBox3DM box);
    @Contract("_ -> new") IBox3I[] transform(IBox3IC... box);
    @Contract("_ -> _") IBox3IM[] transform(IBox3IM... box);
    @Contract("_ -> new") IBox3D[] transform(IBox3DC... box);
    @Contract("_ -> _") IBox3DM[] transform(IBox3DM... box);
    @Contract("-> new") IMatrix3DM toMutable();
    @Contract("-> this") IMatrix3D toImmutable();
    @Contract("-> new") IMatrix3F toFloat();
    @Contract("-> new") IMatrix3D copy();
}