package com.artur114.bananalib.math.m3d.matrix;

import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.matrix.IMatrix3DC;
import com.artur114.bananalib.math.core.m3d.matrix.IMatrix3FC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import org.jetbrains.annotations.Contract;

public interface IMatrix3FM extends IMatrix3F {
    IMatrix3FM set(float m00, float m01, float m02, float m03, float m10, float m11, float m12, float m13, float m20, float m21, float m22, float m23);
    IMatrix3FM set(IMatrix3FC matrix);
    IMatrix3FM set(IMatrix3DC matrix);
    IMatrix3FM set(float[] ms);
    IMatrix3FM setM00(float m00);
    IMatrix3FM setM01(float m01);
    IMatrix3FM setM02(float m02);
    IMatrix3FM setM03(float m03);
    IMatrix3FM setM10(float m10);
    IMatrix3FM setM11(float m11);
    IMatrix3FM setM12(float m12);
    IMatrix3FM setM13(float m13);
    IMatrix3FM setM20(float m20);
    IMatrix3FM setM21(float m21);
    IMatrix3FM setM22(float m22);
    IMatrix3FM setM23(float m23);
    IMatrix3FM setIdentity();
    IMatrix3FM collapseStack();
    IMatrix3FM resetStack();
    IMatrix3FM pushMatrix();
    IMatrix3FM popMatrix();
    @Contract("-> this")
    IMatrix3FM invert();
    @Contract("-> this")
    IMatrix3FM transpose();
    IMatrix3FM mul(IMatrix3DC matrix);
    IMatrix3FM mul(IMatrix3FC matrix);
    IMatrix3FM mulPost(IMatrix3DC matrix);
    IMatrix3FM mulPost(IMatrix3FC matrix);
    IMatrix3FM div(int val);
    IMatrix3FM div(float val);
    IMatrix3FM div(double val);
    IMatrix3FM scale(int val);
    IMatrix3FM scale(float val);
    IMatrix3FM scale(double val);
    IMatrix3FM scale(int x, int y, int z);
    IMatrix3FM scale(float x, float y, float z);
    IMatrix3FM scale(double x, double y, double z);
    IMatrix3FM scale(IVec3DC vec);
    IMatrix3FM scale(IVec3IC vec);
    IMatrix3FM scale(IVec2IC vec, int z);
    IMatrix3FM scale(IVec2IC vec, double z);
    IMatrix3FM scale(IVec2DC vec, int z);
    IMatrix3FM scale(IVec2DC vec, double z);
    IMatrix3FM scale(IVec2IC vec);
    IMatrix3FM scale(IVec2DC vec);
    IMatrix3FM translate(int x, int y, int z);
    IMatrix3FM translate(float x, float y, float z);
    IMatrix3FM translate(double x, double y, double z);
    IMatrix3FM translate(IVec3DC vec);
    IMatrix3FM translate(IVec3IC vec);
    IMatrix3FM translate(IVec2IC vec, int z);
    IMatrix3FM translate(IVec2IC vec, double z);
    IMatrix3FM translate(IVec2DC vec, int z);
    IMatrix3FM translate(IVec2DC vec, double z);
    IMatrix3FM translate(IVec2IC vec);
    IMatrix3FM translate(IVec2DC vec);
    IMatrix3FM rotateX(float degrees);
    IMatrix3FM rotateY(float degrees);
    IMatrix3FM rotateZ(float degrees);
    IMatrix3FM rotate(float degrees, int x, int y, int z);
    IMatrix3FM rotate(float degrees, float x, float y, float z);
    IMatrix3FM rotate(float degrees, double x, double y, double z);
    IMatrix3FM rotate(float degrees, IVec3DC vec);
    IMatrix3FM rotate(float degrees, IVec3IC vec);
    IMatrix3FM rotate(float degrees, IVec2IC vec, int z);
    IMatrix3FM rotate(float degrees, IVec2IC vec, double z);
    IMatrix3FM rotate(float degrees, IVec2DC vec, int z);
    IMatrix3FM rotate(float degrees, IVec2DC vec, double z);
    IMatrix3FM rotate(float degrees, IVec2IC vec);
    IMatrix3FM rotate(float degrees, IVec2DC vec);
    IMatrix3FM rotateXAround(int x, int y, int z, float degrees);
    IMatrix3FM rotateXAround(float x, float y, float z, float degrees);
    IMatrix3FM rotateXAround(double x, double y, double z, float degrees);
    IMatrix3FM rotateXAround(IVec3IC point, float degrees);
    IMatrix3FM rotateXAround(IVec3DC point, float degrees);
    IMatrix3FM rotateXAround(IVec2IC vec, int z, float degrees);
    IMatrix3FM rotateXAround(IVec2IC vec, double z, float degrees);
    IMatrix3FM rotateXAround(IVec2DC vec, int z, float degrees);
    IMatrix3FM rotateXAround(IVec2DC vec, double z, float degrees);
    IMatrix3FM rotateXAround(IVec2IC vec, float degrees);
    IMatrix3FM rotateXAround(IVec2DC vec, float degrees);
    IMatrix3FM rotateYAround(int x, int y, int z, float degrees);
    IMatrix3FM rotateYAround(float x, float y, float z, float degrees);
    IMatrix3FM rotateYAround(double x, double y, double z, float degrees);
    IMatrix3FM rotateYAround(IVec3IC point, float degrees);
    IMatrix3FM rotateYAround(IVec3DC point, float degrees);
    IMatrix3FM rotateYAround(IVec2IC vec, int z, float degrees);
    IMatrix3FM rotateYAround(IVec2IC vec, double z, float degrees);
    IMatrix3FM rotateYAround(IVec2DC vec, int z, float degrees);
    IMatrix3FM rotateYAround(IVec2DC vec, double z, float degrees);
    IMatrix3FM rotateYAround(IVec2IC vec, float degrees);
    IMatrix3FM rotateYAround(IVec2DC vec, float degrees);
    IMatrix3FM rotateZAround(int x, int y, int z, float degrees);
    IMatrix3FM rotateZAround(float x, float y, float z, float degrees);
    IMatrix3FM rotateZAround(double x, double y, double z, float degrees);
    IMatrix3FM rotateZAround(IVec3IC point, float degrees);
    IMatrix3FM rotateZAround(IVec3DC point, float degrees);
    IMatrix3FM rotateZAround(IVec2IC vec, int z, float degrees);
    IMatrix3FM rotateZAround(IVec2IC vec, double z, float degrees);
    IMatrix3FM rotateZAround(IVec2DC vec, int z, float degrees);
    IMatrix3FM rotateZAround(IVec2DC vec, double z, float degrees);
    IMatrix3FM rotateZAround(IVec2IC vec, float degrees);
    IMatrix3FM rotateZAround(IVec2DC vec, float degrees);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, int x, int y, int z);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, float x, float y, float z);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, double x, double y, double z);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, IVec3DC vec);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, IVec3IC vec);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, IVec2IC vec, int z);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, IVec2IC vec, double z);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, IVec2DC vec, int z);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, IVec2DC vec, double z);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, IVec2IC vec);
    IMatrix3FM rotateAround(IVec3DC point, float degrees, IVec2DC vec);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, int x, int y, int z);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, float x, float y, float z);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, double x, double y, double z);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, IVec3DC vec);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, IVec3IC vec);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, IVec2IC vec, int z);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, IVec2IC vec, double z);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, IVec2DC vec, int z);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, IVec2DC vec, double z);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, IVec2IC vec);
    IMatrix3FM rotateAround(IVec3IC point, float degrees, IVec2DC vec);
    IMatrix3FM localScale(int val);
    IMatrix3FM localScale(float val);
    IMatrix3FM localScale(double val);
    IMatrix3FM localScale(int x, int y, int z);
    IMatrix3FM localScale(float x, float y, float z);
    IMatrix3FM localScale(double x, double y, double z);
    IMatrix3FM localScale(IVec3DC vec);
    IMatrix3FM localScale(IVec3IC vec);
    IMatrix3FM localScale(IVec2IC vec, int z);
    IMatrix3FM localScale(IVec2IC vec, double z);
    IMatrix3FM localScale(IVec2DC vec, int z);
    IMatrix3FM localScale(IVec2DC vec, double z);
    IMatrix3FM localScale(IVec2IC vec);
    IMatrix3FM localScale(IVec2DC vec);
    IMatrix3FM localTranslate(int x, int y, int z);
    IMatrix3FM localTranslate(float x, float y, float z);
    IMatrix3FM localTranslate(double x, double y, double z);
    IMatrix3FM localTranslate(IVec3DC vec);
    IMatrix3FM localTranslate(IVec3IC vec);
    IMatrix3FM localTranslate(IVec2IC vec, int z);
    IMatrix3FM localTranslate(IVec2IC vec, double z);
    IMatrix3FM localTranslate(IVec2DC vec, int z);
    IMatrix3FM localTranslate(IVec2DC vec, double z);
    IMatrix3FM localTranslate(IVec2IC vec);
    IMatrix3FM localTranslate(IVec2DC vec);
    IMatrix3FM localRotateX(float degrees);
    IMatrix3FM localRotateY(float degrees);
    IMatrix3FM localRotateZ(float degrees);
    IMatrix3FM localRotate(float degrees, int x, int y, int z);
    IMatrix3FM localRotate(float degrees, float x, float y, float z);
    IMatrix3FM localRotate(float degrees, double x, double y, double z);
    IMatrix3FM localRotate(float degrees, IVec3DC vec);
    IMatrix3FM localRotate(float degrees, IVec3IC vec);
    IMatrix3FM localRotate(float degrees, IVec2IC vec, int z);
    IMatrix3FM localRotate(float degrees, IVec2IC vec, double z);
    IMatrix3FM localRotate(float degrees, IVec2DC vec, int z);
    IMatrix3FM localRotate(float degrees, IVec2DC vec, double z);
    IMatrix3FM localRotate(float degrees, IVec2IC vec);
    IMatrix3FM localRotate(float degrees, IVec2DC vec);
    IMatrix3FM localRotateXAround(int x, int y, int z, float degrees);
    IMatrix3FM localRotateXAround(float x, float y, float z, float degrees);
    IMatrix3FM localRotateXAround(double x, double y, double z, float degrees);
    IMatrix3FM localRotateXAround(IVec3IC point, float degrees);
    IMatrix3FM localRotateXAround(IVec3DC point, float degrees);
    IMatrix3FM localRotateXAround(IVec2IC vec, int z, float degrees);
    IMatrix3FM localRotateXAround(IVec2IC vec, double z, float degrees);
    IMatrix3FM localRotateXAround(IVec2DC vec, int z, float degrees);
    IMatrix3FM localRotateXAround(IVec2DC vec, double z, float degrees);
    IMatrix3FM localRotateXAround(IVec2IC vec, float degrees);
    IMatrix3FM localRotateXAround(IVec2DC vec, float degrees);
    IMatrix3FM localRotateYAround(int x, int y, int z, float degrees);
    IMatrix3FM localRotateYAround(float x, float y, float z, float degrees);
    IMatrix3FM localRotateYAround(double x, double y, double z, float degrees);
    IMatrix3FM localRotateYAround(IVec3IC point, float degrees);
    IMatrix3FM localRotateYAround(IVec3DC point, float degrees);
    IMatrix3FM localRotateYAround(IVec2IC vec, int z, float degrees);
    IMatrix3FM localRotateYAround(IVec2IC vec, double z, float degrees);
    IMatrix3FM localRotateYAround(IVec2DC vec, int z, float degrees);
    IMatrix3FM localRotateYAround(IVec2DC vec, double z, float degrees);
    IMatrix3FM localRotateYAround(IVec2IC vec, float degrees);
    IMatrix3FM localRotateYAround(IVec2DC vec, float degrees);
    IMatrix3FM localRotateZAround(int x, int y, int z, float degrees);
    IMatrix3FM localRotateZAround(float x, float y, float z, float degrees);
    IMatrix3FM localRotateZAround(double x, double y, double z, float degrees);
    IMatrix3FM localRotateZAround(IVec3IC point, float degrees);
    IMatrix3FM localRotateZAround(IVec3DC point, float degrees);
    IMatrix3FM localRotateZAround(IVec2IC vec, int z, float degrees);
    IMatrix3FM localRotateZAround(IVec2IC vec, double z, float degrees);
    IMatrix3FM localRotateZAround(IVec2DC vec, int z, float degrees);
    IMatrix3FM localRotateZAround(IVec2DC vec, double z, float degrees);
    IMatrix3FM localRotateZAround(IVec2IC vec, float degrees);
    IMatrix3FM localRotateZAround(IVec2DC vec, float degrees);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, int x, int y, int z);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, float x, float y, float z);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, double x, double y, double z);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, IVec3DC vec);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, IVec3IC vec);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, IVec2IC vec, int z);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, IVec2IC vec, double z);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, IVec2DC vec, int z);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, IVec2DC vec, double z);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, IVec2IC vec);
    IMatrix3FM localRotateAround(IVec3DC point, float degrees, IVec2DC vec);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, int x, int y, int z);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, float x, float y, float z);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, double x, double y, double z);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, IVec3DC vec);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, IVec3IC vec);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, IVec2IC vec, int z);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, IVec2IC vec, double z);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, IVec2DC vec, int z);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, IVec2DC vec, double z);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, IVec2IC vec);
    IMatrix3FM localRotateAround(IVec3IC point, float degrees, IVec2DC vec);
    @Contract("-> this") IMatrix3FM toMutable();
    @Contract("-> new") IMatrix3F toImmutable();
    @Contract("-> new") IMatrix3DM toDouble();
    @Contract("-> new") IMatrix3FM copy();
}
