package com.artur114.bananalib.math.m3d.matrix;


import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.matrix.IMatrix3DC;
import com.artur114.bananalib.math.core.m3d.matrix.IMatrix3FC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import org.jetbrains.annotations.Contract;

public interface IMatrix3DM extends IMatrix3D {
    IMatrix3DM set(double m00, double m01, double m02, double m03, double m10, double m11, double m12, double m13, double m20, double m21, double m22, double m23);
    IMatrix3DM set(IMatrix3FC matrix);
    IMatrix3DM set(IMatrix3DC matrix);
    IMatrix3DM set(double[] ms);
    IMatrix3DM setM00(double m00);
    IMatrix3DM setM01(double m01);
    IMatrix3DM setM02(double m02);
    IMatrix3DM setM03(double m03);
    IMatrix3DM setM10(double m10);
    IMatrix3DM setM11(double m11);
    IMatrix3DM setM12(double m12);
    IMatrix3DM setM13(double m13);
    IMatrix3DM setM20(double m20);
    IMatrix3DM setM21(double m21);
    IMatrix3DM setM22(double m22);
    IMatrix3DM setM23(double m23);
    IMatrix3DM setIdentity();
    IMatrix3DM collapseStack();
    IMatrix3DM resetStack();
    IMatrix3DM pushMatrix();
    IMatrix3DM popMatrix();
    @Contract("-> this")
    IMatrix3DM invert();
    @Contract("-> this")
    IMatrix3DM transpose();
    IMatrix3DM mul(IMatrix3DC matrix);
    IMatrix3DM mul(IMatrix3FC matrix);
    IMatrix3DM mulPost(IMatrix3DC matrix);
    IMatrix3DM mulPost(IMatrix3FC matrix);
    IMatrix3DM div(int val);
    IMatrix3DM div(double val);
    IMatrix3DM scale(int val);
    IMatrix3DM scale(double val);
    IMatrix3DM scale(int x, int y, int z);
    IMatrix3DM scale(double x, double y, double z);
    IMatrix3DM scale(IVec3DC vec);
    IMatrix3DM scale(IVec3IC vec);
    IMatrix3DM scale(IVec2IC vec, int z);
    IMatrix3DM scale(IVec2IC vec, double z);
    IMatrix3DM scale(IVec2DC vec, int z);
    IMatrix3DM scale(IVec2DC vec, double z);
    IMatrix3DM scale(IVec2IC vec);
    IMatrix3DM scale(IVec2DC vec);
    IMatrix3DM translate(int x, int y, int z);
    IMatrix3DM translate(double x, double y, double z);
    IMatrix3DM translate(IVec3DC vec);
    IMatrix3DM translate(IVec3IC vec);
    IMatrix3DM translate(IVec2IC vec, int z);
    IMatrix3DM translate(IVec2IC vec, double z);
    IMatrix3DM translate(IVec2DC vec, int z);
    IMatrix3DM translate(IVec2DC vec, double z);
    IMatrix3DM translate(IVec2IC vec);
    IMatrix3DM translate(IVec2DC vec);
    IMatrix3DM rotateX(double degrees);
    IMatrix3DM rotateY(double degrees);
    IMatrix3DM rotateZ(double degrees);
    IMatrix3DM rotate(double degrees, int x, int y, int z);
    IMatrix3DM rotate(double degrees, double x, double y, double z);
    IMatrix3DM rotate(double degrees, IVec3DC vec);
    IMatrix3DM rotate(double degrees, IVec3IC vec);
    IMatrix3DM rotate(double degrees, IVec2IC vec, int z);
    IMatrix3DM rotate(double degrees, IVec2IC vec, double z);
    IMatrix3DM rotate(double degrees, IVec2DC vec, int z);
    IMatrix3DM rotate(double degrees, IVec2DC vec, double z);
    IMatrix3DM rotate(double degrees, IVec2IC vec);
    IMatrix3DM rotate(double degrees, IVec2DC vec);
    IMatrix3DM rotateXAround(int x, int y, int z, double degrees);
    IMatrix3DM rotateXAround(double x, double y, double z, double degrees);
    IMatrix3DM rotateXAround(IVec3IC point, double degrees);
    IMatrix3DM rotateXAround(IVec3DC point, double degrees);
    IMatrix3DM rotateXAround(IVec2IC vec, int z, double degrees);
    IMatrix3DM rotateXAround(IVec2IC vec, double z, double degrees);
    IMatrix3DM rotateXAround(IVec2DC vec, int z, double degrees);
    IMatrix3DM rotateXAround(IVec2DC vec, double z, double degrees);
    IMatrix3DM rotateXAround(IVec2IC vec, double degrees);
    IMatrix3DM rotateXAround(IVec2DC vec, double degrees);
    IMatrix3DM rotateYAround(int x, int y, int z, double degrees);
    IMatrix3DM rotateYAround(double x, double y, double z, double degrees);
    IMatrix3DM rotateYAround(IVec3IC point, double degrees);
    IMatrix3DM rotateYAround(IVec3DC point, double degrees);
    IMatrix3DM rotateYAround(IVec2IC vec, int z, double degrees);
    IMatrix3DM rotateYAround(IVec2IC vec, double z, double degrees);
    IMatrix3DM rotateYAround(IVec2DC vec, int z, double degrees);
    IMatrix3DM rotateYAround(IVec2DC vec, double z, double degrees);
    IMatrix3DM rotateYAround(IVec2IC vec, double degrees);
    IMatrix3DM rotateYAround(IVec2DC vec, double degrees);
    IMatrix3DM rotateZAround(int x, int y, int z, double degrees);
    IMatrix3DM rotateZAround(double x, double y, double z, double degrees);
    IMatrix3DM rotateZAround(IVec3IC point, double degrees);
    IMatrix3DM rotateZAround(IVec3DC point, double degrees);
    IMatrix3DM rotateZAround(IVec2IC vec, int z, double degrees);
    IMatrix3DM rotateZAround(IVec2IC vec, double z, double degrees);
    IMatrix3DM rotateZAround(IVec2DC vec, int z, double degrees);
    IMatrix3DM rotateZAround(IVec2DC vec, double z, double degrees);
    IMatrix3DM rotateZAround(IVec2IC vec, double degrees);
    IMatrix3DM rotateZAround(IVec2DC vec, double degrees);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, int x, int y, int z);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, double x, double y, double z);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, IVec3DC vec);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, IVec3IC vec);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, IVec2IC vec, int z);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, IVec2IC vec, double z);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, IVec2DC vec, int z);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, IVec2DC vec, double z);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, IVec2IC vec);
    IMatrix3DM rotateAround(IVec3DC point, double degrees, IVec2DC vec);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, int x, int y, int z);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, double x, double y, double z);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, IVec3DC vec);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, IVec3IC vec);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, IVec2IC vec, int z);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, IVec2IC vec, double z);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, IVec2DC vec, int z);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, IVec2DC vec, double z);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, IVec2IC vec);
    IMatrix3DM rotateAround(IVec3IC point, double degrees, IVec2DC vec);
    IMatrix3DM localScale(int val);
    IMatrix3DM localScale(double val);
    IMatrix3DM localScale(int x, int y, int z);
    IMatrix3DM localScale(double x, double y, double z);
    IMatrix3DM localScale(IVec3DC vec);
    IMatrix3DM localScale(IVec3IC vec);
    IMatrix3DM localScale(IVec2IC vec, int z);
    IMatrix3DM localScale(IVec2IC vec, double z);
    IMatrix3DM localScale(IVec2DC vec, int z);
    IMatrix3DM localScale(IVec2DC vec, double z);
    IMatrix3DM localScale(IVec2IC vec);
    IMatrix3DM localScale(IVec2DC vec);
    IMatrix3DM localTranslate(int x, int y, int z);
    IMatrix3DM localTranslate(double x, double y, double z);
    IMatrix3DM localTranslate(IVec3DC vec);
    IMatrix3DM localTranslate(IVec3IC vec);
    IMatrix3DM localTranslate(IVec2IC vec, int z);
    IMatrix3DM localTranslate(IVec2IC vec, double z);
    IMatrix3DM localTranslate(IVec2DC vec, int z);
    IMatrix3DM localTranslate(IVec2DC vec, double z);
    IMatrix3DM localTranslate(IVec2IC vec);
    IMatrix3DM localTranslate(IVec2DC vec);
    IMatrix3DM localRotateX(double degrees);
    IMatrix3DM localRotateY(double degrees);
    IMatrix3DM localRotateZ(double degrees);
    IMatrix3DM localRotate(double degrees, int x, int y, int z);
    IMatrix3DM localRotate(double degrees, double x, double y, double z);
    IMatrix3DM localRotate(double degrees, IVec3DC vec);
    IMatrix3DM localRotate(double degrees, IVec3IC vec);
    IMatrix3DM localRotate(double degrees, IVec2IC vec, int z);
    IMatrix3DM localRotate(double degrees, IVec2IC vec, double z);
    IMatrix3DM localRotate(double degrees, IVec2DC vec, int z);
    IMatrix3DM localRotate(double degrees, IVec2DC vec, double z);
    IMatrix3DM localRotate(double degrees, IVec2IC vec);
    IMatrix3DM localRotate(double degrees, IVec2DC vec);
    IMatrix3DM localRotateXAround(int x, int y, int z, double degrees);
    IMatrix3DM localRotateXAround(double x, double y, double z, double degrees);
    IMatrix3DM localRotateXAround(IVec3IC point, double degrees);
    IMatrix3DM localRotateXAround(IVec3DC point, double degrees);
    IMatrix3DM localRotateXAround(IVec2IC vec, int z, double degrees);
    IMatrix3DM localRotateXAround(IVec2IC vec, double z, double degrees);
    IMatrix3DM localRotateXAround(IVec2DC vec, int z, double degrees);
    IMatrix3DM localRotateXAround(IVec2DC vec, double z, double degrees);
    IMatrix3DM localRotateXAround(IVec2IC vec, double degrees);
    IMatrix3DM localRotateXAround(IVec2DC vec, double degrees);
    IMatrix3DM localRotateYAround(int x, int y, int z, double degrees);
    IMatrix3DM localRotateYAround(double x, double y, double z, double degrees);
    IMatrix3DM localRotateYAround(IVec3IC point, double degrees);
    IMatrix3DM localRotateYAround(IVec3DC point, double degrees);
    IMatrix3DM localRotateYAround(IVec2IC vec, int z, double degrees);
    IMatrix3DM localRotateYAround(IVec2IC vec, double z, double degrees);
    IMatrix3DM localRotateYAround(IVec2DC vec, int z, double degrees);
    IMatrix3DM localRotateYAround(IVec2DC vec, double z, double degrees);
    IMatrix3DM localRotateYAround(IVec2IC vec, double degrees);
    IMatrix3DM localRotateYAround(IVec2DC vec, double degrees);
    IMatrix3DM localRotateZAround(int x, int y, int z, double degrees);
    IMatrix3DM localRotateZAround(double x, double y, double z, double degrees);
    IMatrix3DM localRotateZAround(IVec3IC point, double degrees);
    IMatrix3DM localRotateZAround(IVec3DC point, double degrees);
    IMatrix3DM localRotateZAround(IVec2IC vec, int z, double degrees);
    IMatrix3DM localRotateZAround(IVec2IC vec, double z, double degrees);
    IMatrix3DM localRotateZAround(IVec2DC vec, int z, double degrees);
    IMatrix3DM localRotateZAround(IVec2DC vec, double z, double degrees);
    IMatrix3DM localRotateZAround(IVec2IC vec, double degrees);
    IMatrix3DM localRotateZAround(IVec2DC vec, double degrees);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, int x, int y, int z);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, double x, double y, double z);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, IVec3DC vec);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, IVec3IC vec);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, IVec2IC vec, int z);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, IVec2IC vec, double z);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, IVec2DC vec, int z);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, IVec2DC vec, double z);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, IVec2IC vec);
    IMatrix3DM localRotateAround(IVec3DC point, double degrees, IVec2DC vec);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, int x, int y, int z);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, double x, double y, double z);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, IVec3DC vec);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, IVec3IC vec);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, IVec2IC vec, int z);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, IVec2IC vec, double z);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, IVec2DC vec, int z);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, IVec2DC vec, double z);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, IVec2IC vec);
    IMatrix3DM localRotateAround(IVec3IC point, double degrees, IVec2DC vec);
    @Contract("-> this") IMatrix3DM toMutable();
    @Contract("-> new") IMatrix3D toImmutable();
    @Contract("-> new") IMatrix3FM toFloat();
    @Contract("-> new") IMatrix3DM copy();
}
