package com.artur114.bananalib.math.m3d.matrix;

import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.matrix.IMatrix3DC;
import com.artur114.bananalib.math.core.m3d.matrix.IMatrix3FC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2DM;
import com.artur114.bananalib.math.m2d.vec.IVec2I;
import com.artur114.bananalib.math.m2d.vec.IVec2IM;
import com.artur114.bananalib.math.m3d.box.IBox3D;
import com.artur114.bananalib.math.m3d.box.IBox3DM;
import com.artur114.bananalib.math.m3d.box.IBox3I;
import com.artur114.bananalib.math.m3d.box.IBox3IM;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3DM;
import com.artur114.bananalib.math.m3d.vec.IVec3I;
import com.artur114.bananalib.math.m3d.vec.IVec3IM;
import org.jetbrains.annotations.Contract;


public interface IMatrix3F extends IMatrix3FC {
    @Contract("-> new")
    IMatrix3F invert();
    @Contract("-> new")
    IMatrix3F transpose();
    IMatrix3F mul(IMatrix3DC matrix);
    IMatrix3F mul(IMatrix3FC matrix);
    IMatrix3F mulPost(IMatrix3DC matrix);
    IMatrix3F mulPost(IMatrix3FC matrix);
    IMatrix3F div(int val);
    IMatrix3F div(float val);
    IMatrix3F div(double val);
    IMatrix3F scale(int val);
    IMatrix3F scale(float val);
    IMatrix3F scale(double val);
    IMatrix3F scale(int x, int y, int z);
    IMatrix3F scale(float x, float y, float z);
    IMatrix3F scale(double x, double y, double z);
    IMatrix3F scale(IVec3DC vec);
    IMatrix3F scale(IVec3IC vec);
    IMatrix3F scale(IVec2IC vec, int z);
    IMatrix3F scale(IVec2IC vec, double z);
    IMatrix3F scale(IVec2DC vec, int z);
    IMatrix3F scale(IVec2DC vec, double z);
    IMatrix3F scale(IVec2IC vec);
    IMatrix3F scale(IVec2DC vec);
    IMatrix3F translate(int x, int y, int z);
    IMatrix3F translate(float x, float y, float z);
    IMatrix3F translate(double x, double y, double z);
    IMatrix3F translate(IVec3DC vec);
    IMatrix3F translate(IVec3IC vec);
    IMatrix3F translate(IVec2IC vec, int z);
    IMatrix3F translate(IVec2IC vec, double z);
    IMatrix3F translate(IVec2DC vec, int z);
    IMatrix3F translate(IVec2DC vec, double z);
    IMatrix3F translate(IVec2IC vec);
    IMatrix3F translate(IVec2DC vec);
    IMatrix3F rotateX(float degrees);
    IMatrix3F rotateY(float degrees);
    IMatrix3F rotateZ(float degrees);
    IMatrix3F rotate(float degrees, int x, int y, int z);
    IMatrix3F rotate(float degrees, float x, float y, float z);
    IMatrix3F rotate(float degrees, double x, double y, double z);
    IMatrix3F rotate(float degrees, IVec3DC vec);
    IMatrix3F rotate(float degrees, IVec3IC vec);
    IMatrix3F rotate(float degrees, IVec2IC vec, int z);
    IMatrix3F rotate(float degrees, IVec2IC vec, double z);
    IMatrix3F rotate(float degrees, IVec2DC vec, int z);
    IMatrix3F rotate(float degrees, IVec2DC vec, double z);
    IMatrix3F rotate(float degrees, IVec2IC vec);
    IMatrix3F rotate(float degrees, IVec2DC vec);
    IMatrix3F rotateXAround(int x, int y, int z, float degrees);
    IMatrix3F rotateXAround(float x, float y, float z, float degrees);
    IMatrix3F rotateXAround(double x, double y, double z, float degrees);
    IMatrix3F rotateXAround(IVec3IC point, float degrees);
    IMatrix3F rotateXAround(IVec3DC point, float degrees);
    IMatrix3F rotateXAround(IVec2IC vec, int z, float degrees);
    IMatrix3F rotateXAround(IVec2IC vec, double z, float degrees);
    IMatrix3F rotateXAround(IVec2DC vec, int z, float degrees);
    IMatrix3F rotateXAround(IVec2DC vec, double z, float degrees);
    IMatrix3F rotateXAround(IVec2IC vec, float degrees);
    IMatrix3F rotateXAround(IVec2DC vec, float degrees);
    IMatrix3F rotateYAround(int x, int y, int z, float degrees);
    IMatrix3F rotateYAround(float x, float y, float z, float degrees);
    IMatrix3F rotateYAround(double x, double y, double z, float degrees);
    IMatrix3F rotateYAround(IVec3IC point, float degrees);
    IMatrix3F rotateYAround(IVec3DC point, float degrees);
    IMatrix3F rotateYAround(IVec2IC vec, int z, float degrees);
    IMatrix3F rotateYAround(IVec2IC vec, double z, float degrees);
    IMatrix3F rotateYAround(IVec2DC vec, int z, float degrees);
    IMatrix3F rotateYAround(IVec2DC vec, double z, float degrees);
    IMatrix3F rotateYAround(IVec2IC vec, float degrees);
    IMatrix3F rotateYAround(IVec2DC vec, float degrees);
    IMatrix3F rotateZAround(int x, int y, int z, float degrees);
    IMatrix3F rotateZAround(float x, float y, float z, float degrees);
    IMatrix3F rotateZAround(double x, double y, double z, float degrees);
    IMatrix3F rotateZAround(IVec3IC point, float degrees);
    IMatrix3F rotateZAround(IVec3DC point, float degrees);
    IMatrix3F rotateZAround(IVec2IC vec, int z, float degrees);
    IMatrix3F rotateZAround(IVec2IC vec, double z, float degrees);
    IMatrix3F rotateZAround(IVec2DC vec, int z, float degrees);
    IMatrix3F rotateZAround(IVec2DC vec, double z, float degrees);
    IMatrix3F rotateZAround(IVec2IC vec, float degrees);
    IMatrix3F rotateZAround(IVec2DC vec, float degrees);
    IMatrix3F rotateAround(IVec3DC point, float degrees, int x, int y, int z);
    IMatrix3F rotateAround(IVec3DC point, float degrees, float x, float y, float z);
    IMatrix3F rotateAround(IVec3DC point, float degrees, double x, double y, double z);
    IMatrix3F rotateAround(IVec3DC point, float degrees, IVec3DC vec);
    IMatrix3F rotateAround(IVec3DC point, float degrees, IVec3IC vec);
    IMatrix3F rotateAround(IVec3DC point, float degrees, IVec2IC vec, int z);
    IMatrix3F rotateAround(IVec3DC point, float degrees, IVec2IC vec, double z);
    IMatrix3F rotateAround(IVec3DC point, float degrees, IVec2DC vec, int z);
    IMatrix3F rotateAround(IVec3DC point, float degrees, IVec2DC vec, double z);
    IMatrix3F rotateAround(IVec3DC point, float degrees, IVec2IC vec);
    IMatrix3F rotateAround(IVec3DC point, float degrees, IVec2DC vec);
    IMatrix3F rotateAround(IVec3IC point, float degrees, int x, int y, int z);
    IMatrix3F rotateAround(IVec3IC point, float degrees, float x, float y, float z);
    IMatrix3F rotateAround(IVec3IC point, float degrees, double x, double y, double z);
    IMatrix3F rotateAround(IVec3IC point, float degrees, IVec3DC vec);
    IMatrix3F rotateAround(IVec3IC point, float degrees, IVec3IC vec);
    IMatrix3F rotateAround(IVec3IC point, float degrees, IVec2IC vec, int z);
    IMatrix3F rotateAround(IVec3IC point, float degrees, IVec2IC vec, double z);
    IMatrix3F rotateAround(IVec3IC point, float degrees, IVec2DC vec, int z);
    IMatrix3F rotateAround(IVec3IC point, float degrees, IVec2DC vec, double z);
    IMatrix3F rotateAround(IVec3IC point, float degrees, IVec2IC vec);
    IMatrix3F rotateAround(IVec3IC point, float degrees, IVec2DC vec);
    IMatrix3F localScale(int val);
    IMatrix3F localScale(float val);
    IMatrix3F localScale(double val);
    IMatrix3F localScale(int x, int y, int z);
    IMatrix3F localScale(float x, float y, float z);
    IMatrix3F localScale(double x, double y, double z);
    IMatrix3F localScale(IVec3DC vec);
    IMatrix3F localScale(IVec3IC vec);
    IMatrix3F localScale(IVec2IC vec, int z);
    IMatrix3F localScale(IVec2IC vec, double z);
    IMatrix3F localScale(IVec2DC vec, int z);
    IMatrix3F localScale(IVec2DC vec, double z);
    IMatrix3F localScale(IVec2IC vec);
    IMatrix3F localScale(IVec2DC vec);
    IMatrix3F localTranslate(int x, int y, int z);
    IMatrix3F localTranslate(float x, float y, float z);
    IMatrix3F localTranslate(double x, double y, double z);
    IMatrix3F localTranslate(IVec3DC vec);
    IMatrix3F localTranslate(IVec3IC vec);
    IMatrix3F localTranslate(IVec2IC vec, int z);
    IMatrix3F localTranslate(IVec2IC vec, double z);
    IMatrix3F localTranslate(IVec2DC vec, int z);
    IMatrix3F localTranslate(IVec2DC vec, double z);
    IMatrix3F localTranslate(IVec2IC vec);
    IMatrix3F localTranslate(IVec2DC vec);
    IMatrix3F localRotateX(float degrees);
    IMatrix3F localRotateY(float degrees);
    IMatrix3F localRotateZ(float degrees);
    IMatrix3F localRotate(float degrees, int x, int y, int z);
    IMatrix3F localRotate(float degrees, float x, float y, float z);
    IMatrix3F localRotate(float degrees, double x, double y, double z);
    IMatrix3F localRotate(float degrees, IVec3DC vec);
    IMatrix3F localRotate(float degrees, IVec3IC vec);
    IMatrix3F localRotate(float degrees, IVec2IC vec, int z);
    IMatrix3F localRotate(float degrees, IVec2IC vec, double z);
    IMatrix3F localRotate(float degrees, IVec2DC vec, int z);
    IMatrix3F localRotate(float degrees, IVec2DC vec, double z);
    IMatrix3F localRotate(float degrees, IVec2IC vec);
    IMatrix3F localRotate(float degrees, IVec2DC vec);
    IMatrix3F localRotateXAround(int x, int y, int z, float degrees);
    IMatrix3F localRotateXAround(float x, float y, float z, float degrees);
    IMatrix3F localRotateXAround(double x, double y, double z, float degrees);
    IMatrix3F localRotateXAround(IVec3IC point, float degrees);
    IMatrix3F localRotateXAround(IVec3DC point, float degrees);
    IMatrix3F localRotateXAround(IVec2IC vec, int z, float degrees);
    IMatrix3F localRotateXAround(IVec2IC vec, double z, float degrees);
    IMatrix3F localRotateXAround(IVec2DC vec, int z, float degrees);
    IMatrix3F localRotateXAround(IVec2DC vec, double z, float degrees);
    IMatrix3F localRotateXAround(IVec2IC vec, float degrees);
    IMatrix3F localRotateXAround(IVec2DC vec, float degrees);
    IMatrix3F localRotateYAround(int x, int y, int z, float degrees);
    IMatrix3F localRotateYAround(float x, float y, float z, float degrees);
    IMatrix3F localRotateYAround(double x, double y, double z, float degrees);
    IMatrix3F localRotateYAround(IVec3IC point, float degrees);
    IMatrix3F localRotateYAround(IVec3DC point, float degrees);
    IMatrix3F localRotateYAround(IVec2IC vec, int z, float degrees);
    IMatrix3F localRotateYAround(IVec2IC vec, double z, float degrees);
    IMatrix3F localRotateYAround(IVec2DC vec, int z, float degrees);
    IMatrix3F localRotateYAround(IVec2DC vec, double z, float degrees);
    IMatrix3F localRotateYAround(IVec2IC vec, float degrees);
    IMatrix3F localRotateYAround(IVec2DC vec, float degrees);
    IMatrix3F localRotateZAround(int x, int y, int z, float degrees);
    IMatrix3F localRotateZAround(float x, float y, float z, float degrees);
    IMatrix3F localRotateZAround(double x, double y, double z, float degrees);
    IMatrix3F localRotateZAround(IVec3IC point, float degrees);
    IMatrix3F localRotateZAround(IVec3DC point, float degrees);
    IMatrix3F localRotateZAround(IVec2IC vec, int z, float degrees);
    IMatrix3F localRotateZAround(IVec2IC vec, double z, float degrees);
    IMatrix3F localRotateZAround(IVec2DC vec, int z, float degrees);
    IMatrix3F localRotateZAround(IVec2DC vec, double z, float degrees);
    IMatrix3F localRotateZAround(IVec2IC vec, float degrees);
    IMatrix3F localRotateZAround(IVec2DC vec, float degrees);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, int x, int y, int z);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, float x, float y, float z);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, double x, double y, double z);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, IVec3DC vec);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, IVec3IC vec);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, IVec2IC vec, int z);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, IVec2IC vec, double z);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, IVec2DC vec, int z);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, IVec2DC vec, double z);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, IVec2IC vec);
    IMatrix3F localRotateAround(IVec3DC point, float degrees, IVec2DC vec);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, int x, int y, int z);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, float x, float y, float z);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, double x, double y, double z);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, IVec3DC vec);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, IVec3IC vec);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, IVec2IC vec, int z);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, IVec2IC vec, double z);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, IVec2DC vec, int z);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, IVec2DC vec, double z);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, IVec2IC vec);
    IMatrix3F localRotateAround(IVec3IC point, float degrees, IVec2DC vec);
    @Contract("_,_ -> new") IVec2I transform(int x, int y);
    @Contract("_,_ -> new") IVec2D transform(double x, double y);
    @Contract("_,_,_ -> new") IVec3I transform(int x, int y, int z);
    @Contract("_,_,_ -> new") IVec3D transform(double x, double y, double z);
    @Contract("_ -> new") IVec3I transform(IVec3IC vec);
    @Contract("_ -> _") IVec3IM transform(IVec3IM vec);
    @Contract("_ -> new") IVec3D transform(IVec3DC vec);
    @Contract("_ -> _") IVec3DM transform(IVec3DM vec);
    @Contract("_ -> new") IVec3I[] transform(IVec3IC... vec);
    @Contract("_ -> _") IVec3IM[] transform(IVec3IM... vec);
    @Contract("_ -> new") IVec3D[] transform(IVec3DC... vec);
    @Contract("_ -> _") IVec3DM[] transform(IVec3DM... vec);
    @Contract("_ -> new") IVec2I transform(IVec2IC vec);
    @Contract("_ -> _") IVec2IM transform(IVec2IM vec);
    @Contract("_ -> new") IVec2D transform(IVec2DC vec);
    @Contract("_ -> _") IVec2DM transform(IVec2DM vec);
    @Contract("_,_ -> new") IVec3I transform(IVec2IC vec, int z);
    @Contract("_,_ -> new") IVec3D transform(IVec2IC vec, double z);
    @Contract("_,_ -> new") IVec3D transform(IVec2DC vec, int z);
    @Contract("_,_ -> new") IVec3D transform(IVec2DC vec, double z);
    @Contract("_ -> new") IVec2I[] transform(IVec2IC... vec);
    @Contract("_ -> _") IVec2IM[] transform(IVec2IM... vec);
    @Contract("_ -> new") IVec2D[] transform(IVec2DC... vec);
    @Contract("_ -> _") IVec2DM[] transform(IVec2DM... vec);
    @Contract("_ -> new") IBox3I transform(IBox3IC box);
    @Contract("_ -> _") IBox3IM transform(IBox3IM box);
    @Contract("_ -> new") IBox3D transform(IBox3DC box);
    @Contract("_ -> _") IBox3DM transform(IBox3DM box);
    @Contract("_ -> new") IBox3I[] transform(IBox3IC... box);
    @Contract("_ -> _") IBox3IM[] transform(IBox3IM... box);
    @Contract("_ -> new") IBox3D[] transform(IBox3DC... box);
    @Contract("_ -> _") IBox3DM[] transform(IBox3DM... box);
    @Contract("-> new") IMatrix3FM toMutable();
    @Contract("-> this") IMatrix3F toImmutable();
    @Contract("-> new") IMatrix3D toDouble();
    @Contract("-> new") IMatrix3F copy();
}
