package com.artur114.bananalib.mc.math.m3d.vec;

import com.artur114.bananalib.math.core.m2d.box.IBox2DC;
import com.artur114.bananalib.math.core.m2d.box.IBox2IC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import com.artur114.bananalib.math.m3d.vec.IVec3DM;
import com.artur114.bananalib.math.m3d.vec.IVec3IM;
import net.minecraft.entity.Entity;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.math.Vec3i;
import org.jetbrains.annotations.Contract;

public interface IPosMc3IM extends IVec3IM {
    IPosMc3IM set(int[] pos);
    IPosMc3IM set(double x, double y, double z);
    IPosMc3IM set(int x, int y, int z);
    IPosMc3IM set(Vec3i vec);
    IPosMc3IM set(Vec3d vec);
    IPosMc3IM set(Entity source);
    IPosMc3IM set(IVec3IC vec);
    IPosMc3IM set(IVec3DC vec);
    IPosMc3IM set(IVec2DC vec, double z);
    IPosMc3IM set(IVec2DC vec, int z);
    IPosMc3IM set(IVec2IC vec, double z);
    IPosMc3IM set(IVec2IC vec, int z);
    IPosMc3IM set(IVec2DC vec);
    IPosMc3IM set(IVec2IC vec);
    IPosMc3IM setZero();
    IPosMc3IM collapseStack();
    IPosMc3IM resetStack();
    IPosMc3IM pushPos();
    IPosMc3IM popPos();
    IPosMc3IM setX(int x);
    IPosMc3IM setX(double x);
    IPosMc3IM setY(int y);
    IPosMc3IM setY(double y);
    IPosMc3IM setZ(int z);
    IPosMc3IM setZ(double z);
    IPosMc3IM addX(int x);
    IPosMc3IM addY(int y);
    IPosMc3IM addZ(int z);
    int chunkX();
    int chunkZ();
    IPosMc3IM up();
    IPosMc3IM up(int n);
    IPosMc3IM offset(EnumFacing face);
    IPosMc3IM offset(EnumFacing face, int n);
    IPosMc3IM add(int x, int y, int z);
    IPosMc3IM add(double x, double y, double z);
    IPosMc3IM add(Vec3i vec);
    IPosMc3IM add(Vec3d vec);
    IPosMc3IM add(IVec3IC vec);
    IPosMc3IM add(IVec3DC vec);
    IPosMc3IM add(IVec2IC vec, int z);
    IPosMc3IM add(IVec2IC vec, double z);
    IPosMc3IM add(IVec2DC vec, int z);
    IPosMc3IM add(IVec2DC vec, double z);
    IPosMc3IM add(IVec2IC vec);
    IPosMc3IM add(IVec2DC vec);
    IPosMc3IM subtract(int x, int y, int z);
    IPosMc3IM subtract(double x, double y, double z);
    IPosMc3IM subtract(Vec3i vec);
    IPosMc3IM subtract(Vec3d vec);
    IPosMc3IM subtract(IVec3IC vec);
    IPosMc3IM subtract(IVec3DC vec);
    IPosMc3IM subtract(IVec2IC vec, int z);
    IPosMc3IM subtract(IVec2IC vec, double z);
    IPosMc3IM subtract(IVec2DC vec, int z);
    IPosMc3IM subtract(IVec2DC vec, double z);
    IPosMc3IM subtract(IVec2IC vec);
    IPosMc3IM subtract(IVec2DC vec);
    IPosMc3IM scale(int val);
    IPosMc3IM scale(double val);
    IPosMc3IM scale(int x, int y, int z);
    IPosMc3IM scale(double x, double y, double z);
    IPosMc3IM scale(Vec3i vec);
    IPosMc3IM scale(Vec3d vec);
    IPosMc3IM scale(IVec3IC vec);
    IPosMc3IM scale(IVec3DC vec);
    IPosMc3IM scale(IVec2IC vec, int z);
    IPosMc3IM scale(IVec2IC vec, double z);
    IPosMc3IM scale(IVec2DC vec, int z);
    IPosMc3IM scale(IVec2DC vec, double z);
    IPosMc3IM scale(IVec2IC vec);
    IPosMc3IM scale(IVec2DC vec);
    IPosMc3IM divide(int val);
    IPosMc3IM divide(double val);
    IPosMc3IM divide(int x, int y, int z);
    IPosMc3IM divide(double x, double y, double z);
    IPosMc3IM divide(Vec3i vec);
    IPosMc3IM divide(Vec3d vec);
    IPosMc3IM divide(IVec3IC vec);
    IPosMc3IM divide(IVec3DC vec);
    IPosMc3IM divide(IVec2IC vec, int z);
    IPosMc3IM divide(IVec2IC vec, double z);
    IPosMc3IM divide(IVec2DC vec, int z);
    IPosMc3IM divide(IVec2DC vec, double z);
    IPosMc3IM divide(IVec2IC vec);
    IPosMc3IM divide(IVec2DC vec);
    IPosMc3IM rotateX(double degrees);
    IPosMc3IM rotateY(double degrees);
    IPosMc3IM rotateZ(double degrees);
    IPosMc3IM rotateXAround(int x, int y, int z, double degrees);
    IPosMc3IM rotateXAround(double x, double y, double z, double degrees);
    IPosMc3IM rotateXAround(IVec3IC point, double degrees);
    IPosMc3IM rotateXAround(IVec3DC point, double degrees);
    IPosMc3IM rotateYAround(int x, int y, int z, double degrees);
    IPosMc3IM rotateYAround(double x, double y, double z, double degrees);
    IPosMc3IM rotateYAround(IVec3IC point, double degrees);
    IPosMc3IM rotateYAround(IVec3DC point, double degrees);
    IPosMc3IM rotateZAround(int x, int y, int z, double degrees);
    IPosMc3IM rotateZAround(double x, double y, double z, double degrees);
    IPosMc3IM rotateZAround(IVec3IC point, double degrees);
    IPosMc3IM rotateZAround(IVec3DC point, double degrees);
    IPosMc3IM lerp(int x, int y, int z, double delta);
    IPosMc3IM lerp(double x, double y, double z, double delta);
    IPosMc3IM lerp(IVec3IC vec, double delta);
    IPosMc3IM lerp(IVec3DC vec, double delta);
    IPosMc3IM lerp(IVec2IC vec, int z, double delta);
    IPosMc3IM lerp(IVec2IC vec, double z, double delta);
    IPosMc3IM lerp(IVec2DC vec, int z, double delta);
    IPosMc3IM lerp(IVec2DC vec, double z, double delta);
    IPosMc3IM lerp(IVec2IC vec, double delta);
    IPosMc3IM lerp(IVec2DC vec, double delta);
    IPosMc3IM wrap(IBox3IC box);
    IPosMc3IM wrap(IBox3DC box);
    IPosMc3IM wrap(IBox2IC box, int minZ, int maxZ);
    IPosMc3IM wrap(IBox2IC box, double minZ, double maxZ);
    IPosMc3IM wrap(IBox2DC box, int minZ, int maxZ);
    IPosMc3IM wrap(IBox2DC box, double minZ, double maxZ);
    IPosMc3IM wrap(IBox2IC box);
    IPosMc3IM wrap(IBox2DC box);
    IPosMc3IM wrap(int x, int y, int z);
    IPosMc3IM wrap(double x, double y, double z);
    IPosMc3IM wrap(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IPosMc3IM wrap(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IPosMc3IM clamp(IBox3IC box);
    IPosMc3IM clamp(IBox3DC box);
    IPosMc3IM clamp(IBox2IC box, int minZ, int maxZ);
    IPosMc3IM clamp(IBox2IC box, double minZ, double maxZ);
    IPosMc3IM clamp(IBox2DC box, int minZ, int maxZ);
    IPosMc3IM clamp(IBox2DC box, double minZ, double maxZ);
    IPosMc3IM clamp(IBox2IC box);
    IPosMc3IM clamp(IBox2DC box);
    IPosMc3IM clamp(int x, int y, int z);
    IPosMc3IM clamp(double x, double y, double z);
    IPosMc3IM clamp(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IPosMc3IM clamp(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    @Contract("-> new")
    IVec3DM normalize();
    @Contract("-> new")
    IPosMc3IM toMutable();
    @Contract("-> this")
    IPosMc3I toImmutable();
    @Contract("-> new")
    IVec3DM toDouble();
    @Contract("-> new")
    IPosMc3IM copy();
}
