package com.artur114.bananalib.mc.math.m3d.vec;

import com.artur114.bananalib.math.core.m2d.box.IBox2DC;
import com.artur114.bananalib.math.core.m2d.box.IBox2IC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import com.artur114.bananalib.math.m3d.vec.IVec3I;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.math.Vec3i;
import org.jetbrains.annotations.Contract;

public interface IPosMc3I extends IVec3I {
    int chunkX();
    int chunkZ();
    IPosMc3I up();
    IPosMc3I up(int n);
    IPosMc3I offset(EnumFacing face);
    IPosMc3I offset(EnumFacing face, int n);
    IPosMc3I add(int x, int y, int z);
    IPosMc3I add(double x, double y, double z);
    IPosMc3I add(Vec3i vec);
    IPosMc3I add(Vec3d vec);
    IPosMc3I add(IVec3IC vec);
    IPosMc3I add(IVec3DC vec);
    IPosMc3I add(IVec2IC vec, int z);
    IPosMc3I add(IVec2IC vec, double z);
    IPosMc3I add(IVec2DC vec, int z);
    IPosMc3I add(IVec2DC vec, double z);
    IPosMc3I add(IVec2IC vec);
    IPosMc3I add(IVec2DC vec);
    IPosMc3I subtract(int x, int y, int z);
    IPosMc3I subtract(double x, double y, double z);
    IPosMc3I subtract(Vec3i vec);
    IPosMc3I subtract(Vec3d vec);
    IPosMc3I subtract(IVec3IC vec);
    IPosMc3I subtract(IVec3DC vec);
    IPosMc3I subtract(IVec2IC vec, int z);
    IPosMc3I subtract(IVec2IC vec, double z);
    IPosMc3I subtract(IVec2DC vec, int z);
    IPosMc3I subtract(IVec2DC vec, double z);
    IPosMc3I subtract(IVec2IC vec);
    IPosMc3I subtract(IVec2DC vec);
    IPosMc3I scale(int val);
    IPosMc3I scale(double val);
    IPosMc3I scale(int x, int y, int z);
    IPosMc3I scale(double x, double y, double z);
    IPosMc3I scale(Vec3i vec);
    IPosMc3I scale(Vec3d vec);
    IPosMc3I scale(IVec3IC vec);
    IPosMc3I scale(IVec3DC vec);
    IPosMc3I scale(IVec2IC vec, int z);
    IPosMc3I scale(IVec2IC vec, double z);
    IPosMc3I scale(IVec2DC vec, int z);
    IPosMc3I scale(IVec2DC vec, double z);
    IPosMc3I scale(IVec2IC vec);
    IPosMc3I scale(IVec2DC vec);
    IPosMc3I divide(int val);
    IPosMc3I divide(double val);
    IPosMc3I divide(int x, int y, int z);
    IPosMc3I divide(double x, double y, double z);
    IPosMc3I divide(Vec3i vec);
    IPosMc3I divide(Vec3d vec);
    IPosMc3I divide(IVec3IC vec);
    IPosMc3I divide(IVec3DC vec);
    IPosMc3I divide(IVec2IC vec, int z);
    IPosMc3I divide(IVec2IC vec, double z);
    IPosMc3I divide(IVec2DC vec, int z);
    IPosMc3I divide(IVec2DC vec, double z);
    IPosMc3I divide(IVec2IC vec);
    IPosMc3I divide(IVec2DC vec);
    IPosMc3I rotateX(double degrees);
    IPosMc3I rotateY(double degrees);
    IPosMc3I rotateZ(double degrees);
    IPosMc3I rotateXAround(int x, int y, int z, double degrees);
    IPosMc3I rotateXAround(double x, double y, double z, double degrees);
    IPosMc3I rotateXAround(IVec3IC point, double degrees);
    IPosMc3I rotateXAround(IVec3DC point, double degrees);
    IPosMc3I rotateYAround(int x, int y, int z, double degrees);
    IPosMc3I rotateYAround(double x, double y, double z, double degrees);
    IPosMc3I rotateYAround(IVec3IC point, double degrees);
    IPosMc3I rotateYAround(IVec3DC point, double degrees);
    IPosMc3I rotateZAround(int x, int y, int z, double degrees);
    IPosMc3I rotateZAround(double x, double y, double z, double degrees);
    IPosMc3I rotateZAround(IVec3IC point, double degrees);
    IPosMc3I rotateZAround(IVec3DC point, double degrees);
    IPosMc3I lerp(int x, int y, int z, double delta);
    IPosMc3I lerp(double x, double y, double z, double delta);
    IPosMc3I lerp(IVec3IC vec, double delta);
    IPosMc3I lerp(IVec3DC vec, double delta);
    IPosMc3I lerp(IVec2IC vec, int z, double delta);
    IPosMc3I lerp(IVec2IC vec, double z, double delta);
    IPosMc3I lerp(IVec2DC vec, int z, double delta);
    IPosMc3I lerp(IVec2DC vec, double z, double delta);
    IPosMc3I lerp(IVec2IC vec, double delta);
    IPosMc3I lerp(IVec2DC vec, double delta);
    IPosMc3I wrap(IBox3IC box);
    IPosMc3I wrap(IBox3DC box);
    IPosMc3I wrap(IBox2IC box, int minZ, int maxZ);
    IPosMc3I wrap(IBox2IC box, double minZ, double maxZ);
    IPosMc3I wrap(IBox2DC box, int minZ, int maxZ);
    IPosMc3I wrap(IBox2DC box, double minZ, double maxZ);
    IPosMc3I wrap(IBox2IC box);
    IPosMc3I wrap(IBox2DC box);
    IPosMc3I wrap(int x, int y, int z);
    IPosMc3I wrap(double x, double y, double z);
    IPosMc3I wrap(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IPosMc3I wrap(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IPosMc3I clamp(IBox3IC box);
    IPosMc3I clamp(IBox3DC box);
    IPosMc3I clamp(IBox2IC box, int minZ, int maxZ);
    IPosMc3I clamp(IBox2IC box, double minZ, double maxZ);
    IPosMc3I clamp(IBox2DC box, int minZ, int maxZ);
    IPosMc3I clamp(IBox2DC box, double minZ, double maxZ);
    IPosMc3I clamp(IBox2IC box);
    IPosMc3I clamp(IBox2DC box);
    IPosMc3I clamp(int x, int y, int z);
    IPosMc3I clamp(double x, double y, double z);
    IPosMc3I clamp(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IPosMc3I clamp(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    @Contract("-> new")
    IVecMc3D normalize();
    @Contract("-> new")
    IPosMc3IM toMutable();
    @Contract("-> this")
    IPosMc3I toImmutable();
    @Contract("-> new")
    IVecMc3D toDouble();
    @Contract("-> new")
    IPosMc3I copy();
}
