package com.artur114.bananalib.mc.math.m3d.vec;

import com.artur114.bananalib.math.core.m2d.box.IBox2DC;
import com.artur114.bananalib.math.core.m2d.box.IBox2IC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3DM;
import com.artur114.bananalib.math.m3d.vec.IVec3I;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.math.Vec3i;
import org.jetbrains.annotations.Contract;

public interface IVecMc3D extends IVec3D {
    IVecMc3D add(int x, int y, int z);
    IVecMc3D add(double x, double y, double z);
    IVecMc3D add(Vec3i vec);
    IVecMc3D add(Vec3d vec);
    IVecMc3D add(IVec3IC vec);
    IVecMc3D add(IVec3DC vec);
    IVecMc3D add(IVec2IC vec, int z);
    IVecMc3D add(IVec2IC vec, double z);
    IVecMc3D add(IVec2DC vec, int z);
    IVecMc3D add(IVec2DC vec, double z);
    IVecMc3D add(IVec2IC vec);
    IVecMc3D add(IVec2DC vec);
    IVecMc3D subtract(int x, int y, int z);
    IVecMc3D subtract(double x, double y, double z);
    IVecMc3D subtract(Vec3i vec);
    IVecMc3D subtract(Vec3d vec);
    IVecMc3D subtract(IVec3IC vec);
    IVecMc3D subtract(IVec3DC vec);
    IVecMc3D subtract(IVec2IC vec, int z);
    IVecMc3D subtract(IVec2IC vec, double z);
    IVecMc3D subtract(IVec2DC vec, int z);
    IVecMc3D subtract(IVec2DC vec, double z);
    IVecMc3D subtract(IVec2IC vec);
    IVecMc3D subtract(IVec2DC vec);
    IVecMc3D scale(int val);
    IVecMc3D scale(double val);
    IVecMc3D scale(int x, int y, int z);
    IVecMc3D scale(double x, double y, double z);
    IVecMc3D scale(Vec3i vec);
    IVecMc3D scale(Vec3d vec);
    IVecMc3D scale(IVec3IC vec);
    IVecMc3D scale(IVec3DC vec);
    IVecMc3D scale(IVec2IC vec, int z);
    IVecMc3D scale(IVec2IC vec, double z);
    IVecMc3D scale(IVec2DC vec, int z);
    IVecMc3D scale(IVec2DC vec, double z);
    IVecMc3D scale(IVec2IC vec);
    IVecMc3D scale(IVec2DC vec);
    IVecMc3D divide(int val);
    IVecMc3D divide(double val);
    IVecMc3D divide(int x, int y, int z);
    IVecMc3D divide(double x, double y, double z);
    IVecMc3D divide(Vec3i vec);
    IVecMc3D divide(Vec3d vec);
    IVecMc3D divide(IVec3IC vec);
    IVecMc3D divide(IVec3DC vec);
    IVecMc3D divide(IVec2IC vec, int z);
    IVecMc3D divide(IVec2IC vec, double z);
    IVecMc3D divide(IVec2DC vec, int z);
    IVecMc3D divide(IVec2DC vec, double z);
    IVecMc3D divide(IVec2IC vec);
    IVecMc3D divide(IVec2DC vec);
    IVecMc3D rotateX(double degrees);
    IVecMc3D rotateY(double degrees);
    IVecMc3D rotateZ(double degrees);
    IVecMc3D rotateXAround(int x, int y, int z, double degrees);
    IVecMc3D rotateXAround(double x, double y, double z, double degrees);
    IVecMc3D rotateXAround(IVec3IC point, double degrees);
    IVecMc3D rotateXAround(IVec3DC point, double degrees);
    IVecMc3D rotateYAround(int x, int y, int z, double degrees);
    IVecMc3D rotateYAround(double x, double y, double z, double degrees);
    IVecMc3D rotateYAround(IVec3IC point, double degrees);
    IVecMc3D rotateYAround(IVec3DC point, double degrees);
    IVecMc3D rotateZAround(int x, int y, int z, double degrees);
    IVecMc3D rotateZAround(double x, double y, double z, double degrees);
    IVecMc3D rotateZAround(IVec3IC point, double degrees);
    IVecMc3D rotateZAround(IVec3DC point, double degrees);
    IVecMc3D lerp(int x, int y, int z, double delta);
    IVecMc3D lerp(double x, double y, double z, double delta);
    IVecMc3D lerp(IVec3IC vec, double delta);
    IVecMc3D lerp(IVec3DC vec, double delta);
    IVecMc3D lerp(IVec2IC vec, int z, double delta);
    IVecMc3D lerp(IVec2IC vec, double z, double delta);
    IVecMc3D lerp(IVec2DC vec, int z, double delta);
    IVecMc3D lerp(IVec2DC vec, double z, double delta);
    IVecMc3D lerp(IVec2IC vec, double delta);
    IVecMc3D lerp(IVec2DC vec, double delta);
    IVecMc3D wrap(IBox3IC box);
    IVecMc3D wrap(IBox3DC box);
    IVecMc3D wrap(IBox2IC box, int minZ, int maxZ);
    IVecMc3D wrap(IBox2IC box, double minZ, double maxZ);
    IVecMc3D wrap(IBox2DC box, int minZ, int maxZ);
    IVecMc3D wrap(IBox2DC box, double minZ, double maxZ);
    IVecMc3D wrap(IBox2IC box);
    IVecMc3D wrap(IBox2DC box);
    IVecMc3D wrap(int x, int y, int z);
    IVecMc3D wrap(double x, double y, double z);
    IVecMc3D wrap(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVecMc3D wrap(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IVecMc3D clamp(IBox3IC box);
    IVecMc3D clamp(IBox3DC box);
    IVecMc3D clamp(IBox2IC box, int minZ, int maxZ);
    IVecMc3D clamp(IBox2IC box, double minZ, double maxZ);
    IVecMc3D clamp(IBox2DC box, int minZ, int maxZ);
    IVecMc3D clamp(IBox2DC box, double minZ, double maxZ);
    IVecMc3D clamp(IBox2IC box);
    IVecMc3D clamp(IBox2DC box);
    IVecMc3D clamp(int x, int y, int z);
    IVecMc3D clamp(double x, double y, double z);
    IVecMc3D clamp(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVecMc3D clamp(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    @Contract("-> new")
    IVecMc3D normalize();
    @Contract("-> this")
    IVecMc3D toImmutable();
    @Contract("-> new")
    IPosMc3I floor();
    @Contract("-> new")
    IPosMc3I round();
    @Contract("-> new")
    IPosMc3I ceil();
    @Contract("-> new")
    IVecMc3D copy();
}
