package com.artur114.bananalib.math.m2d.matrix;

import com.artur114.bananalib.math.core.m2d.box.IBox2DC;
import com.artur114.bananalib.math.core.m2d.box.IBox2IC;
import com.artur114.bananalib.math.core.m2d.matrix.IMatrix2DC;
import com.artur114.bananalib.math.core.m2d.matrix.IMatrix2FC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.m2d.box.IBox2D;
import com.artur114.bananalib.math.m2d.box.IBox2DM;
import com.artur114.bananalib.math.m2d.box.IBox2I;
import com.artur114.bananalib.math.m2d.box.IBox2IM;
import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2DM;
import com.artur114.bananalib.math.m2d.vec.IVec2I;
import com.artur114.bananalib.math.m2d.vec.IVec2IM;

import java.nio.FloatBuffer;

public interface IMatrix2F extends IMatrix2FC {
    IMatrix2F invert();
    IMatrix2F mul(IMatrix2FC matrix);
    IMatrix2F mul(IMatrix2DC matrix);
    IMatrix2F mulPost(IMatrix2FC matrix);
    IMatrix2F mulPost(IMatrix2DC matrix);
    IMatrix2F scale(int x, int y);
    IMatrix2F scale(float x, float y);
    IMatrix2F scale(double x, double y);
    IMatrix2F scale(IVec2DC vec);
    IMatrix2F scale(IVec2IC vec);
    IMatrix2F translate(int x, int y);
    IMatrix2F translate(float x, float y);
    IMatrix2F translate(double x, double y);
    IMatrix2F translate(IVec2DC vec);
    IMatrix2F translate(IVec2IC vec);
    IMatrix2F rotate(float degrees);
    IMatrix2F rotateAround(int x, int y, float degrees);
    IMatrix2F rotateAround(float x, float y, float degrees);
    IMatrix2F rotateAround(double x, double y, float degrees);
    IMatrix2F rotateAround(IVec2DC point, float degrees);
    IMatrix2F rotateAround(IVec2IC point, float degrees);
    IVec2I transform(int x, int y);
    IVec2D transform(float x, float y);
    IVec2D transform(double x, double y);
    IVec2I transform(IVec2IC vec);
    IVec2IM transform(IVec2IM vec);
    IVec2D transform(IVec2DC vec);
    IVec2DM transform(IVec2DM vec);
    IVec2I[] transform(IVec2IC... vec);
    IVec2IM[] transform(IVec2IM... vec);
    IVec2D[] transform(IVec2DC... vec);
    IVec2DM[] transform(IVec2DM... vec);
    IBox2I transform(IBox2IC box);
    IBox2IM transform(IBox2IM box);
    IBox2D transform(IBox2DC box);
    IBox2DM transform(IBox2DM box);
    IBox2I[] transform(IBox2IC... box);
    IBox2IM[] transform(IBox2IM... box);
    IBox2D[] transform(IBox2DC... box);
    IBox2DM[] transform(IBox2DM... box);
    FloatBuffer writeToBuffer(FloatBuffer buf);
    IMatrix2FM toMutable();
    IMatrix2F toImmutable();
    IMatrix2D toDouble();
}
