package com.artur114.bananalib.math.m3d.vec;

import com.artur114.bananalib.math.m2d.box.IBox2D;
import com.artur114.bananalib.math.m2d.box.IBox2I;
import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2DM;
import com.artur114.bananalib.math.m2d.vec.IVec2I;
import com.artur114.bananalib.math.m2d.vec.IVec2IM;
import com.artur114.bananalib.math.m3d.box.IBox3D;
import com.artur114.bananalib.math.m3d.box.IBox3I;

public interface IVec3I {
    int x();
    int y();
    int z();
    IVec2I xy();
    IVec2I xz();
    IVec2I yx();
    IVec2I yz();
    IVec2I zx();
    IVec2I zy();
    IVec3I zyx();
    IVec3I zxy();
    IVec3I yzx();
    IVec3I xzy();
    IVec3I yxz();
    IVec2IM xy(IVec2IM out);
    IVec2IM xz(IVec2IM out);
    IVec2IM yx(IVec2IM out);
    IVec2IM yz(IVec2IM out);
    IVec2IM zx(IVec2IM out);
    IVec2IM zy(IVec2IM out);
    IVec3IM zyx(IVec3IM out);
    IVec3IM zxy(IVec3IM out);
    IVec3IM yzx(IVec3IM out);
    IVec3IM xzy(IVec3IM out);
    IVec3IM yxz(IVec3IM out);
    float length();
    float lengthSq();
    int dot(IVec3I vec);
    double dot(IVec3D vec);
    IVec3I cross(IVec3I vec);
    IVec3D cross(IVec3D vec);
    float distance(int x, int y, int z);
    float distance(double x, double y, double z);
    float distance(IVec3I vec);
    float distance(IVec3D vec);
    float distanceSq(int x, int y, int z);
    double distanceSq(double x, double y, double z);
    float distanceSq(IVec3I vec);
    double distanceSq(IVec3D vec);
    IVec3I add(int x, int y, int z);
    IVec3I add(double x, double y, double z);
    IVec3I add(IVec3I vec);
    IVec3I add(IVec3D vec);
    IVec3I add(IVec2I vec, int z);
    IVec3I add(IVec2I vec, double z);
    IVec3I add(IVec2D vec, int z);
    IVec3I add(IVec2D vec, double z);
    IVec3I add(IVec2I vec);
    IVec3I add(IVec2D vec);
    IVec3I subtract(int x, int y, int z);
    IVec3I subtract(double x, double y, double z);
    IVec3I subtract(IVec3I vec);
    IVec3I subtract(IVec3D vec);
    IVec3I subtract(IVec2I vec, int z);
    IVec3I subtract(IVec2I vec, double z);
    IVec3I subtract(IVec2D vec, int z);
    IVec3I subtract(IVec2D vec, double z);
    IVec3I subtract(IVec2I vec);
    IVec3I subtract(IVec2D vec);
    IVec3I scale(int val);
    IVec3I scale(double val);
    IVec3I scale(int x, int y, int z);
    IVec3I scale(double x, double y, double z);
    IVec3I scale(IVec3I vec);
    IVec3I scale(IVec3D vec);
    IVec3I scale(IVec2I vec, int z);
    IVec3I scale(IVec2I vec, double z);
    IVec3I scale(IVec2D vec, int z);
    IVec3I scale(IVec2D vec, double z);
    IVec3I scale(IVec2I vec);
    IVec3I scale(IVec2D vec);
    IVec3I divide(int val);
    IVec3I divide(double val);
    IVec3I divide(int x, int y, int z);
    IVec3I divide(double x, double y, double z);
    IVec3I divide(IVec3I vec);
    IVec3I divide(IVec3D vec);
    IVec3I divide(IVec2I vec, int z);
    IVec3I divide(IVec2I vec, double z);
    IVec3I divide(IVec2D vec, int z);
    IVec3I divide(IVec2D vec, double z);
    IVec3I divide(IVec2I vec);
    IVec3I divide(IVec2D vec);
    IVec3I rotateX(double degrees);
    IVec3I rotateY(double degrees);
    IVec3I rotateZ(double degrees);
    IVec3I rotateXAround(int x, int y, int z, double degrees);
    IVec3I rotateXAround(double x, double y, double z, double degrees);
    IVec3I rotateXAround(IVec3I point, double degrees);
    IVec3I rotateXAround(IVec3D point, double degrees);
    IVec3I rotateYAround(int x, int y, int z, double degrees);
    IVec3I rotateYAround(double x, double y, double z, double degrees);
    IVec3I rotateYAround(IVec3I point, double degrees);
    IVec3I rotateYAround(IVec3D point, double degrees);
    IVec3I rotateZAround(int x, int y, int z, double degrees);
    IVec3I rotateZAround(double x, double y, double z, double degrees);
    IVec3I rotateZAround(IVec3I point, double degrees);
    IVec3I rotateZAround(IVec3D point, double degrees);
    IVec3I wrap(IBox3I box);
    IVec3I wrap(IBox3D box);
    IVec3I wrap(IBox2I box, int minZ, int maxZ);
    IVec3I wrap(IBox2I box, double minZ, double maxZ);
    IVec3I wrap(IBox2D box, int minZ, int maxZ);
    IVec3I wrap(IBox2D box, double minZ, double maxZ);
    IVec3I wrap(IBox2I box);
    IVec3I wrap(IBox2D box);
    IVec3I wrap(int x, int y, int z);
    IVec3I wrap(double x, double y, double z);
    IVec3I wrap(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVec3I wrap(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IVec3I clamp(IBox3I box);
    IVec3I clamp(IBox3D box);
    IVec3I clamp(IBox2I box, int minZ, int maxZ);
    IVec3I clamp(IBox2I box, double minZ, double maxZ);
    IVec3I clamp(IBox2D box, int minZ, int maxZ);
    IVec3I clamp(IBox2D box, double minZ, double maxZ);
    IVec3I clamp(IBox2I box);
    IVec3I clamp(IBox2D box);
    IVec3I clamp(int x, int y, int z);
    IVec3I clamp(double x, double y, double z);
    IVec3I clamp(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVec3I clamp(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IVec3D normalize();
    IVec3IM toMutable();
    IVec3I toImmutable();
    IVec3D toDouble();
    IVec3I copy();
}
