package com.artur114.bananalib.math.m3d.vec;

import com.artur114.bananalib.math.core.m2d.box.IBox2DC;
import com.artur114.bananalib.math.core.m2d.box.IBox2IC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import org.jetbrains.annotations.Contract;

public interface IVec3DM extends IVec3D {
    IVec3DM set(double[] pos);
    IVec3DM set(double x, double y, double z);
    IVec3DM set(int x, int y, int z);
    IVec3DM set(IVec3IC vec);
    IVec3DM set(IVec3DC vec);
    IVec3DM set(IVec2DC vec, double z);
    IVec3DM set(IVec2DC vec, int z);
    IVec3DM set(IVec2IC vec, double z);
    IVec3DM set(IVec2IC vec, int z);
    IVec3DM set(IVec2DC vec);
    IVec3DM set(IVec2IC vec);
    IVec3DM setZero();
    IVec3DM collapseStack();
    IVec3DM resetStack();
    IVec3DM pushPos();
    IVec3DM popPos();
    IVec3DM setX(int x);
    IVec3DM setX(double x);
    IVec3DM setY(int y);
    IVec3DM setY(double y);
    IVec3DM setZ(int z);
    IVec3DM setZ(double z);
    IVec3DM add(int x, int y, int z);
    IVec3DM add(double x, double y, double z);
    IVec3DM add(IVec3IC vec);
    IVec3DM add(IVec3DC vec);
    IVec3DM add(IVec2IC vec, int z);
    IVec3DM add(IVec2IC vec, double z);
    IVec3DM add(IVec2DC vec, int z);
    IVec3DM add(IVec2DC vec, double z);
    IVec3DM add(IVec2IC vec);
    IVec3DM add(IVec2DC vec);
    IVec3DM subtract(int x, int y, int z);
    IVec3DM subtract(double x, double y, double z);
    IVec3DM subtract(IVec3IC vec);
    IVec3DM subtract(IVec3DC vec);
    IVec3DM subtract(IVec2IC vec, int z);
    IVec3DM subtract(IVec2IC vec, double z);
    IVec3DM subtract(IVec2DC vec, int z);
    IVec3DM subtract(IVec2DC vec, double z);
    IVec3DM subtract(IVec2IC vec);
    IVec3DM subtract(IVec2DC vec);
    IVec3DM scale(int val);
    IVec3DM scale(double val);
    IVec3DM scale(int x, int y, int z);
    IVec3DM scale(double x, double y, double z);
    IVec3DM scale(IVec3IC vec);
    IVec3DM scale(IVec3DC vec);
    IVec3DM scale(IVec2IC vec, int z);
    IVec3DM scale(IVec2IC vec, double z);
    IVec3DM scale(IVec2DC vec, int z);
    IVec3DM scale(IVec2DC vec, double z);
    IVec3DM scale(IVec2IC vec);
    IVec3DM scale(IVec2DC vec);
    IVec3DM divide(int val);
    IVec3DM divide(double val);
    IVec3DM divide(int x, int y, int z);
    IVec3DM divide(double x, double y, double z);
    IVec3DM divide(IVec3IC vec);
    IVec3DM divide(IVec3DC vec);
    IVec3DM divide(IVec2IC vec, int z);
    IVec3DM divide(IVec2IC vec, double z);
    IVec3DM divide(IVec2DC vec, int z);
    IVec3DM divide(IVec2DC vec, double z);
    IVec3DM divide(IVec2IC vec);
    IVec3DM divide(IVec2DC vec);
    IVec3DM rotateX(double degrees);
    IVec3DM rotateY(double degrees);
    IVec3DM rotateZ(double degrees);
    IVec3DM rotateXAround(int x, int y, int z, double degrees);
    IVec3DM rotateXAround(double x, double y, double z, double degrees);
    IVec3DM rotateXAround(IVec3IC point, double degrees);
    IVec3DM rotateXAround(IVec3DC point, double degrees);
    IVec3DM rotateYAround(int x, int y, int z, double degrees);
    IVec3DM rotateYAround(double x, double y, double z, double degrees);
    IVec3DM rotateYAround(IVec3IC point, double degrees);
    IVec3DM rotateYAround(IVec3DC point, double degrees);
    IVec3DM rotateZAround(int x, int y, int z, double degrees);
    IVec3DM rotateZAround(double x, double y, double z, double degrees);
    IVec3DM rotateZAround(IVec3IC point, double degrees);
    IVec3DM rotateZAround(IVec3DC point, double degrees);
    IVec3DM lerp(int x, int y, int z, double delta);
    IVec3DM lerp(double x, double y, double z, double delta);
    IVec3DM lerp(IVec3IC vec, double delta);
    IVec3DM lerp(IVec3DC vec, double delta);
    IVec3DM lerp(IVec2IC vec, int z, double delta);
    IVec3DM lerp(IVec2IC vec, double z, double delta);
    IVec3DM lerp(IVec2DC vec, int z, double delta);
    IVec3DM lerp(IVec2DC vec, double z, double delta);
    IVec3DM lerp(IVec2IC vec, double delta);
    IVec3DM lerp(IVec2DC vec, double delta);
    IVec3DM wrap(IBox3IC box);
    IVec3DM wrap(IBox3DC box);
    IVec3DM wrap(IBox2IC box, int minZ, int maxZ);
    IVec3DM wrap(IBox2IC box, double minZ, double maxZ);
    IVec3DM wrap(IBox2DC box, int minZ, int maxZ);
    IVec3DM wrap(IBox2DC box, double minZ, double maxZ);
    IVec3DM wrap(IBox2IC box);
    IVec3DM wrap(IBox2DC box);
    IVec3DM wrap(int x, int y, int z);
    IVec3DM wrap(double x, double y, double z);
    IVec3DM wrap(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVec3DM wrap(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IVec3DM clamp(IBox3IC box);
    IVec3DM clamp(IBox3DC box);
    IVec3DM clamp(IBox2IC box, int minZ, int maxZ);
    IVec3DM clamp(IBox2IC box, double minZ, double maxZ);
    IVec3DM clamp(IBox2DC box, int minZ, int maxZ);
    IVec3DM clamp(IBox2DC box, double minZ, double maxZ);
    IVec3DM clamp(IBox2IC box);
    IVec3DM clamp(IBox2DC box);
    IVec3DM clamp(int x, int y, int z);
    IVec3DM clamp(double x, double y, double z);
    IVec3DM clamp(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVec3DM clamp(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    @Contract("-> new")
    IVec3D toImmutable();
    @Contract("-> this")
    IVec3DM toMutable();
    @Contract("-> this")
    IVec3DM normalize();
    @Contract("-> new")
    IVec3IM floor();
    @Contract("-> new")
    IVec3IM round();
    @Contract("-> new")
    IVec3IM ceil();
    @Contract("-> new")
    IVec3DM copy();
}
