package com.artur114.bananalib.math.m3d.vec;

import com.artur114.bananalib.math.core.m2d.box.IBox2DC;
import com.artur114.bananalib.math.core.m2d.box.IBox2IC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import org.jetbrains.annotations.Contract;

public interface IVec3IM extends IVec3I {
    IVec3IM set(int[] pos);
    IVec3IM set(double x, double y, double z);
    IVec3IM set(int x, int y, int z);
    IVec3IM set(IVec3IC vec);
    IVec3IM set(IVec3DC vec);
    IVec3IM set(IVec2DC vec, double z);
    IVec3IM set(IVec2DC vec, int z);
    IVec3IM set(IVec2IC vec, double z);
    IVec3IM set(IVec2IC vec, int z);
    IVec3IM set(IVec2DC vec);
    IVec3IM set(IVec2IC vec);
    IVec3IM setZero();
    IVec3IM collapseStack();
    IVec3IM resetStack();
    IVec3IM pushPos();
    IVec3IM popPos();
    IVec3IM setX(int x);
    IVec3IM setX(double x);
    IVec3IM setY(int y);
    IVec3IM setY(double y);
    IVec3IM setZ(int z);
    IVec3IM setZ(double z);
    IVec3IM add(int x, int y, int z);
    IVec3IM add(double x, double y, double z);
    IVec3IM add(IVec3IC vec);
    IVec3IM add(IVec3DC vec);
    IVec3IM add(IVec2IC vec, int z);
    IVec3IM add(IVec2IC vec, double z);
    IVec3IM add(IVec2DC vec, int z);
    IVec3IM add(IVec2DC vec, double z);
    IVec3IM add(IVec2IC vec);
    IVec3IM add(IVec2DC vec);
    IVec3IM subtract(int x, int y, int z);
    IVec3IM subtract(double x, double y, double z);
    IVec3IM subtract(IVec3IC vec);
    IVec3IM subtract(IVec3DC vec);
    IVec3IM subtract(IVec2IC vec, int z);
    IVec3IM subtract(IVec2IC vec, double z);
    IVec3IM subtract(IVec2DC vec, int z);
    IVec3IM subtract(IVec2DC vec, double z);
    IVec3IM subtract(IVec2IC vec);
    IVec3IM subtract(IVec2DC vec);
    IVec3IM scale(int val);
    IVec3IM scale(double val);
    IVec3IM scale(int x, int y, int z);
    IVec3IM scale(double x, double y, double z);
    IVec3IM scale(IVec3IC vec);
    IVec3IM scale(IVec3DC vec);
    IVec3IM scale(IVec2IC vec, int z);
    IVec3IM scale(IVec2IC vec, double z);
    IVec3IM scale(IVec2DC vec, int z);
    IVec3IM scale(IVec2DC vec, double z);
    IVec3IM scale(IVec2IC vec);
    IVec3IM scale(IVec2DC vec);
    IVec3IM divide(int val);
    IVec3IM divide(double val);
    IVec3IM divide(int x, int y, int z);
    IVec3IM divide(double x, double y, double z);
    IVec3IM divide(IVec3IC vec);
    IVec3IM divide(IVec3DC vec);
    IVec3IM divide(IVec2IC vec, int z);
    IVec3IM divide(IVec2IC vec, double z);
    IVec3IM divide(IVec2DC vec, int z);
    IVec3IM divide(IVec2DC vec, double z);
    IVec3IM divide(IVec2IC vec);
    IVec3IM divide(IVec2DC vec);
    IVec3IM rotateX(double degrees);
    IVec3IM rotateY(double degrees);
    IVec3IM rotateZ(double degrees);
    IVec3IM rotateXAround(int x, int y, int z, double degrees);
    IVec3IM rotateXAround(double x, double y, double z, double degrees);
    IVec3IM rotateXAround(IVec3IC point, double degrees);
    IVec3IM rotateXAround(IVec3DC point, double degrees);
    IVec3IM rotateYAround(int x, int y, int z, double degrees);
    IVec3IM rotateYAround(double x, double y, double z, double degrees);
    IVec3IM rotateYAround(IVec3IC point, double degrees);
    IVec3IM rotateYAround(IVec3DC point, double degrees);
    IVec3IM rotateZAround(int x, int y, int z, double degrees);
    IVec3IM rotateZAround(double x, double y, double z, double degrees);
    IVec3IM rotateZAround(IVec3IC point, double degrees);
    IVec3IM rotateZAround(IVec3DC point, double degrees);
    IVec3IM lerp(int x, int y, int z, double delta);
    IVec3IM lerp(double x, double y, double z, double delta);
    IVec3IM lerp(IVec3IC vec, double delta);
    IVec3IM lerp(IVec3DC vec, double delta);
    IVec3IM lerp(IVec2IC vec, int z, double delta);
    IVec3IM lerp(IVec2IC vec, double z, double delta);
    IVec3IM lerp(IVec2DC vec, int z, double delta);
    IVec3IM lerp(IVec2DC vec, double z, double delta);
    IVec3IM lerp(IVec2IC vec, double delta);
    IVec3IM lerp(IVec2DC vec, double delta);
    IVec3IM wrap(IBox3IC box);
    IVec3IM wrap(IBox3DC box);
    IVec3IM wrap(IBox2IC box, int minZ, int maxZ);
    IVec3IM wrap(IBox2IC box, double minZ, double maxZ);
    IVec3IM wrap(IBox2DC box, int minZ, int maxZ);
    IVec3IM wrap(IBox2DC box, double minZ, double maxZ);
    IVec3IM wrap(IBox2IC box);
    IVec3IM wrap(IBox2DC box);
    IVec3IM wrap(int x, int y, int z);
    IVec3IM wrap(double x, double y, double z);
    IVec3IM wrap(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVec3IM wrap(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IVec3IM clamp(IBox3IC box);
    IVec3IM clamp(IBox3DC box);
    IVec3IM clamp(IBox2IC box, int minZ, int maxZ);
    IVec3IM clamp(IBox2IC box, double minZ, double maxZ);
    IVec3IM clamp(IBox2DC box, int minZ, int maxZ);
    IVec3IM clamp(IBox2DC box, double minZ, double maxZ);
    IVec3IM clamp(IBox2IC box);
    IVec3IM clamp(IBox2DC box);
    IVec3IM clamp(int x, int y, int z);
    IVec3IM clamp(double x, double y, double z);
    IVec3IM clamp(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IVec3IM clamp(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    @Contract("-> this")
    IVec3IM toMutable();
    @Contract("-> new")
    IVec3I toImmutable();
    @Contract("-> new")
    IVec3DM normalize();
    @Contract("-> new")
    IVec3DM toDouble();
    @Contract("-> new")
    IVec3IM copy();
}
