package com.artur114.bananalib.mc.math.m3d.box;

import com.artur114.bananalib.math.core.m2d.box.IBox2DC;
import com.artur114.bananalib.math.core.m2d.box.IBox2IC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import com.artur114.bananalib.math.m3d.box.IBox3D;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.math.Vec3i;

public interface IAbbMc3D extends IBox3D {
    boolean contains(AxisAlignedBB box);
    boolean contains(Vec3d vec);
    boolean contains(Vec3i vec);
    IAbbMc3D grow(double amount);
    IAbbMc3D grow(double x, double y, double z);
    IAbbMc3D grow(int amount);
    IAbbMc3D grow(int x, int y, int z);
    IAbbMc3D grow(Vec3d vec);
    IAbbMc3D grow(Vec3i vec);
    IAbbMc3D grow(IVec3IC vec);
    IAbbMc3D grow(IVec3DC vec);
    IAbbMc3D grow(IVec2IC vec, int z);
    IAbbMc3D grow(IVec2IC vec, double z);
    IAbbMc3D grow(IVec2DC vec, int z);
    IAbbMc3D grow(IVec2DC vec, double z);
    IAbbMc3D grow(IVec2IC vec);
    IAbbMc3D grow(IVec2DC vec);
    IAbbMc3D offset(int x, int y, int z);
    IAbbMc3D offset(double x, double y, double z);
    IAbbMc3D offset(Vec3d vec);
    IAbbMc3D offset(Vec3i vec);
    IAbbMc3D offset(IVec3IC vec);
    IAbbMc3D offset(IVec3DC vec);
    IAbbMc3D offset(IVec2IC vec, int z);
    IAbbMc3D offset(IVec2IC vec, double z);
    IAbbMc3D offset(IVec2DC vec, int z);
    IAbbMc3D offset(IVec2DC vec, double z);
    IAbbMc3D offset(IVec2IC vec);
    IAbbMc3D offset(IVec2DC vec);
    IAbbMc3D include(int x, int y, int z);
    IAbbMc3D include(double x, double y, double z);
    IAbbMc3D include(Vec3d vec);
    IAbbMc3D include(Vec3i vec);
    IAbbMc3D include(IVec3IC vec);
    IAbbMc3D include(IVec3DC vec);
    IAbbMc3D include(IVec2IC vec, int z);
    IAbbMc3D include(IVec2IC vec, double z);
    IAbbMc3D include(IVec2DC vec, int z);
    IAbbMc3D include(IVec2DC vec, double z);
    IAbbMc3D include(IVec2IC vec);
    IAbbMc3D include(IVec2DC vec);
    IAbbMc3D union(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IAbbMc3D union(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IAbbMc3D union(Vec3i boxFrom, Vec3i boxTo);
    IAbbMc3D union(Vec3d boxFrom, Vec3d boxTo);
    IAbbMc3D union(AxisAlignedBB box);
    IAbbMc3D union(IVec3DC boxFrom, IVec3DC boxTo);
    IAbbMc3D union(IVec3IC boxFrom, IVec3IC boxTo);
    IAbbMc3D union(IBox3DC box);
    IAbbMc3D union(IBox3IC box);
    IAbbMc3D union(IBox2IC box, int minZ, int maxZ);
    IAbbMc3D union(IBox2IC box, double minZ, double maxZ);
    IAbbMc3D union(IBox2DC box, int minZ, int maxZ);
    IAbbMc3D union(IBox2DC box, double minZ, double maxZ);
    IAbbMc3D union(IBox2IC box);
    IAbbMc3D union(IBox2DC box);
    IAbbMc3D intersection(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IAbbMc3D intersection(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IAbbMc3D intersection(Vec3i boxFrom, Vec3i boxTo);
    IAbbMc3D intersection(Vec3d boxFrom, Vec3d boxTo);
    IAbbMc3D intersection(AxisAlignedBB box);
    IAbbMc3D intersection(IVec3DC boxFrom, IVec3DC boxTo);
    IAbbMc3D intersection(IVec3IC boxFrom, IVec3IC boxTo);
    IAbbMc3D intersection(IBox3DC box);
    IAbbMc3D intersection(IBox3IC box);
    IAbbMc3D intersection(IBox2IC box, int minZ, int maxZ);
    IAbbMc3D intersection(IBox2IC box, double minZ, double maxZ);
    IAbbMc3D intersection(IBox2DC box, int minZ, int maxZ);
    IAbbMc3D intersection(IBox2DC box, double minZ, double maxZ);
    IAbbMc3D intersection(IBox2IC box);
    IAbbMc3D intersection(IBox2DC box);
}
