buildscript {
    repositories {
        mavenCentral()
        maven {url = "https://maven.minecraftforge.net"}
    }
    dependencies {
        classpath("com.anatawa12.forge:ForgeGradle:2.3-1.0.+") {
            changing = true
        }
    }
}
plugins {
    id 'maven-publish'
    id 'java-library'
}
apply plugin: 'net.minecraftforge.gradle.forge'

group = 'com.artur114.bananalib'
version = mcVersion

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    mavenCentral()
}

minecraft {
    version = "1.12.2-14.23.5.2847"
    mappings = "snapshot_20171003"
}

dependencies {
    implementation project(':math')
    implementation project(':util')
    testImplementation project(':math')
}

apply from: rootProject.file("scripts/base.gradle")
apply from: rootProject.file("scripts/publish.gradle")
apply from: rootProject.file("scripts/groovy.gradle")