package com.artur114.bananalib.math.m3d.box;

import com.artur114.bananalib.math.m2d.box.IBox2D;
import com.artur114.bananalib.math.m2d.box.IBox2I;
import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2I;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3I;

public interface IBox3I {
    int minX();
    int minY();
    int minZ();
    int maxX();
    int maxY();
    int maxZ();
    int size();
    boolean contains(int x, int y, int z);
    boolean contains(double x, double y, double z);
    boolean contains(IBox3I box);
    boolean contains(IBox3D box);
    boolean contains(IVec3I vec);
    boolean contains(IVec3D vec);
    boolean contains(IVec2I vec, int z);
    boolean contains(IVec2I vec, double z);
    boolean contains(IVec2D vec, int z);
    boolean contains(IVec2D vec, double z);
    boolean contains(IVec2I vec);
    boolean contains(IVec2D vec);
    boolean contains(IBox2I box, int minZ, int maxZ);
    boolean contains(IBox2I box, double minZ, double maxZ);
    boolean contains(IBox2D box, int minZ, int maxZ);
    boolean contains(IBox2D box, double minZ, double maxZ);
    boolean contains(IBox2I box);
    boolean contains(IBox2D box);
    boolean intersects(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    boolean intersects(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    boolean intersects(IVec3D boxFrom, IVec3D boxTo);
    boolean intersects(IVec3I boxFrom, IVec3I boxTo);
    boolean intersects(IBox3D box);
    boolean intersects(IBox3I box);
    boolean intersects(IBox2I box, int minZ, int maxZ);
    boolean intersects(IBox2I box, double minZ, double maxZ);
    boolean intersects(IBox2D box, int minZ, int maxZ);
    boolean intersects(IBox2D box, double minZ, double maxZ);
    boolean intersects(IBox2I box);
    boolean intersects(IBox2D box);
    IBox3I grow(double amount);
    IBox3I grow(double x, double y, double z);
    IBox3I grow(int amount);
    IBox3I grow(int x, int y, int z);
    IBox3I grow(IVec3I vec);
    IBox3I grow(IVec3D vec);
    IBox3I grow(IVec2I vec, int z);
    IBox3I grow(IVec2I vec, double z);
    IBox3I grow(IVec2D vec, int z);
    IBox3I grow(IVec2D vec, double z);
    IBox3I grow(IVec2I vec);
    IBox3I grow(IVec2D vec);
    IBox3I offset(int x, int y, int z);
    IBox3I offset(double x, double y, double z);
    IBox3I offset(IVec3I vec);
    IBox3I offset(IVec3D vec);
    IBox3I offset(IVec2I vec, int z);
    IBox3I offset(IVec2I vec, double z);
    IBox3I offset(IVec2D vec, int z);
    IBox3I offset(IVec2D vec, double z);
    IBox3I offset(IVec2I vec);
    IBox3I offset(IVec2D vec);
    IBox3I include(int x, int y, int z);
    IBox3I include(double x, double y, double z);
    IBox3I include(IVec3I vec);
    IBox3I include(IVec3D vec);
    IBox3I include(IVec2I vec, int z);
    IBox3I include(IVec2I vec, double z);
    IBox3I include(IVec2D vec, int z);
    IBox3I include(IVec2D vec, double z);
    IBox3I include(IVec2I vec);
    IBox3I include(IVec2D vec);
    IBox3I union(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3I union(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3I union(IVec3D boxFrom, IVec3D boxTo);
    IBox3I union(IVec3I boxFrom, IVec3I boxTo);
    IBox3I union(IBox3D box);
    IBox3I union(IBox3I box);
    IBox3I union(IBox2I box, int minZ, int maxZ);
    IBox3I union(IBox2I box, double minZ, double maxZ);
    IBox3I union(IBox2D box, int minZ, int maxZ);
    IBox3I union(IBox2D box, double minZ, double maxZ);
    IBox3I union(IBox2I box);
    IBox3I union(IBox2D box);
    IBox3I intersection(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3I intersection(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3I intersection(IVec3D boxFrom, IVec3D boxTo);
    IBox3I intersection(IVec3I boxFrom, IVec3I boxTo);
    IBox3I intersection(IBox3D box);
    IBox3I intersection(IBox3I box);
    IBox3I intersection(IBox2I box, int minZ, int maxZ);
    IBox3I intersection(IBox2I box, double minZ, double maxZ);
    IBox3I intersection(IBox2D box, int minZ, int maxZ);
    IBox3I intersection(IBox2D box, double minZ, double maxZ);
    IBox3I intersection(IBox2I box);
    IBox3I intersection(IBox2D box);
    IBox3IM toMutable();
    IBox3I toImmutable();
    IBox3D toDouble();
    IBox3I copy();
}
