package com.artur114.bananalib.math.m3d.box;

import com.artur114.bananalib.math.m2d.box.IBox2D;
import com.artur114.bananalib.math.m2d.box.IBox2I;
import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2I;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3I;

public interface IBox3IM extends IBox3I {
    IBox3IM set(int[] box);
    IBox3IM set(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3IM set(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3IM set(IVec3D boxFrom, IVec3D boxTo);
    IBox3IM set(IVec3I boxFrom, IVec3I boxTo);
    IBox3IM set(IBox3D box);
    IBox3IM set(IBox3I box);
    IBox3IM set(IBox2I box, int minZ, int maxZ);
    IBox3IM set(IBox2I box, double minZ, double maxZ);
    IBox3IM set(IBox2D box, int minZ, int maxZ);
    IBox3IM set(IBox2D box, double minZ, double maxZ);
    IBox3IM set(IBox2I box);
    IBox3IM set(IBox2D box);
    IBox3IM setZero();
    IBox3IM collapseStack();
    IBox3IM resetStack();
    IBox3IM pushBox();
    IBox3IM popBox();
    IBox3IM grow(double amount);
    IBox3IM grow(double x, double y, double z);
    IBox3IM grow(int amount);
    IBox3IM grow(int x, int y, int z);
    IBox3IM grow(IVec3I vec);
    IBox3IM grow(IVec3D vec);
    IBox3IM grow(IVec2I vec, int z);
    IBox3IM grow(IVec2I vec, double z);
    IBox3IM grow(IVec2D vec, int z);
    IBox3IM grow(IVec2D vec, double z);
    IBox3IM grow(IVec2I vec);
    IBox3IM grow(IVec2D vec);
    IBox3IM offset(int x, int y, int z);
    IBox3IM offset(double x, double y, double z);
    IBox3IM offset(IVec3I vec);
    IBox3IM offset(IVec3D vec);
    IBox3IM offset(IVec2I vec, int z);
    IBox3IM offset(IVec2I vec, double z);
    IBox3IM offset(IVec2D vec, int z);
    IBox3IM offset(IVec2D vec, double z);
    IBox3IM offset(IVec2I vec);
    IBox3IM offset(IVec2D vec);
    IBox3IM include(int x, int y, int z);
    IBox3IM include(double x, double y, double z);
    IBox3IM include(IVec3I vec);
    IBox3IM include(IVec3D vec);
    IBox3IM include(IVec2I vec, int z);
    IBox3IM include(IVec2I vec, double z);
    IBox3IM include(IVec2D vec, int z);
    IBox3IM include(IVec2D vec, double z);
    IBox3IM include(IVec2I vec);
    IBox3IM include(IVec2D vec);
    IBox3IM union(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3IM union(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3IM union(IVec3D boxFrom, IVec3D boxTo);
    IBox3IM union(IVec3I boxFrom, IVec3I boxTo);
    IBox3IM union(IBox3D box);
    IBox3IM union(IBox3I box);
    IBox3IM union(IBox2I box, int minZ, int maxZ);
    IBox3IM union(IBox2I box, double minZ, double maxZ);
    IBox3IM union(IBox2D box, int minZ, int maxZ);
    IBox3IM union(IBox2D box, double minZ, double maxZ);
    IBox3IM union(IBox2I box);
    IBox3IM union(IBox2D box);
    IBox3IM intersection(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3IM intersection(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3IM intersection(IVec3D boxFrom, IVec3D boxTo);
    IBox3IM intersection(IVec3I boxFrom, IVec3I boxTo);
    IBox3IM intersection(IBox3D box);
    IBox3IM intersection(IBox3I box);
    IBox3IM intersection(IBox2I box, int minZ, int maxZ);
    IBox3IM intersection(IBox2I box, double minZ, double maxZ);
    IBox3IM intersection(IBox2D box, int minZ, int maxZ);
    IBox3IM intersection(IBox2D box, double minZ, double maxZ);
    IBox3IM intersection(IBox2I box);
    IBox3IM intersection(IBox2D box);
    IBox3DM toDouble();
    IBox3IM copy();
}
