package com.artur114.bananalib.math.m3d.box;

import com.artur114.bananalib.math.m2d.box.IBox2D;
import com.artur114.bananalib.math.m2d.box.IBox2I;
import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2I;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3I;

public interface IBox3D {
    double minX();
    double minY();
    double minZ();
    double maxX();
    double maxY();
    double maxZ();
    double size();
    boolean contains(int x, int y, int z);
    boolean contains(double x, double y, double z);
    boolean contains(IBox3I box);
    boolean contains(IBox3D box);
    boolean contains(IVec3I vec);
    boolean contains(IVec3D vec);
    boolean contains(IVec2I vec, int z);
    boolean contains(IVec2I vec, double z);
    boolean contains(IVec2D vec, int z);
    boolean contains(IVec2D vec, double z);
    boolean contains(IVec2I vec);
    boolean contains(IVec2D vec);
    boolean contains(IBox2I box, int minZ, int maxZ);
    boolean contains(IBox2I box, double minZ, double maxZ);
    boolean contains(IBox2D box, int minZ, int maxZ);
    boolean contains(IBox2D box, double minZ, double maxZ);
    boolean contains(IBox2I box);
    boolean contains(IBox2D box);
    boolean intersects(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    boolean intersects(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    boolean intersects(IVec3D boxFrom, IVec3D boxTo);
    boolean intersects(IVec3I boxFrom, IVec3I boxTo);
    boolean intersects(IBox3D box);
    boolean intersects(IBox3I box);
    boolean intersects(IBox2I box, int minZ, int maxZ);
    boolean intersects(IBox2I box, double minZ, double maxZ);
    boolean intersects(IBox2D box, int minZ, int maxZ);
    boolean intersects(IBox2D box, double minZ, double maxZ);
    boolean intersects(IBox2I box);
    boolean intersects(IBox2D box);
    IBox3D grow(double amount);
    IBox3D grow(double x, double y, double z);
    IBox3D grow(int amount);
    IBox3D grow(int x, int y, int z);
    IBox3D grow(IVec3I vec);
    IBox3D grow(IVec3D vec);
    IBox3D grow(IVec2I vec, int z);
    IBox3D grow(IVec2I vec, double z);
    IBox3D grow(IVec2D vec, int z);
    IBox3D grow(IVec2D vec, double z);
    IBox3D grow(IVec2I vec);
    IBox3D grow(IVec2D vec);
    IBox3D offset(int x, int y, int z);
    IBox3D offset(double x, double y, double z);
    IBox3D offset(IVec3I vec);
    IBox3D offset(IVec3D vec);
    IBox3D offset(IVec2I vec, int z);
    IBox3D offset(IVec2I vec, double z);
    IBox3D offset(IVec2D vec, int z);
    IBox3D offset(IVec2D vec, double z);
    IBox3D offset(IVec2I vec);
    IBox3D offset(IVec2D vec);
    IBox3D include(int x, int y, int z);
    IBox3D include(double x, double y, double z);
    IBox3D include(IVec3I vec);
    IBox3D include(IVec3D vec);
    IBox3D include(IVec2I vec, int z);
    IBox3D include(IVec2I vec, double z);
    IBox3D include(IVec2D vec, int z);
    IBox3D include(IVec2D vec, double z);
    IBox3D include(IVec2I vec);
    IBox3D include(IVec2D vec);
    IBox3D union(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3D union(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3D union(IVec3D boxFrom, IVec3D boxTo);
    IBox3D union(IVec3I boxFrom, IVec3I boxTo);
    IBox3D union(IBox3D box);
    IBox3D union(IBox3I box);
    IBox3D union(IBox2I box, int minZ, int maxZ);
    IBox3D union(IBox2I box, double minZ, double maxZ);
    IBox3D union(IBox2D box, int minZ, int maxZ);
    IBox3D union(IBox2D box, double minZ, double maxZ);
    IBox3D union(IBox2I box);
    IBox3D union(IBox2D box);
    IBox3D intersection(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3D intersection(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3D intersection(IVec3D boxFrom, IVec3D boxTo);
    IBox3D intersection(IVec3I boxFrom, IVec3I boxTo);
    IBox3D intersection(IBox3D box);
    IBox3D intersection(IBox3I box);
    IBox3D intersection(IBox2I box, int minZ, int maxZ);
    IBox3D intersection(IBox2I box, double minZ, double maxZ);
    IBox3D intersection(IBox2D box, int minZ, int maxZ);
    IBox3D intersection(IBox2D box, double minZ, double maxZ);
    IBox3D intersection(IBox2I box);
    IBox3D intersection(IBox2D box);
    IBox3DM toMutable();
    IBox3D toImmutable();
    IBox3I floor();
    IBox3I round();
    IBox3I ceil();
    IBox3D copy();
}
