package com.artur114.bananalib.math.m3d.box;

import com.artur114.bananalib.math.m2d.box.IBox2D;
import com.artur114.bananalib.math.m2d.box.IBox2I;
import com.artur114.bananalib.math.m2d.vec.IVec2D;
import com.artur114.bananalib.math.m2d.vec.IVec2I;
import com.artur114.bananalib.math.m3d.vec.IVec3D;
import com.artur114.bananalib.math.m3d.vec.IVec3I;

public interface IBox3DM extends IBox3D {
    IBox3DM set(double[] box);
    IBox3DM set(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3DM set(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3DM set(IVec3D boxFrom, IVec3D boxTo);
    IBox3DM set(IVec3I boxFrom, IVec3I boxTo);
    IBox3DM set(IBox3D box);
    IBox3DM set(IBox3I box);
    IBox3DM set(IBox2I box, int minZ, int maxZ);
    IBox3DM set(IBox2I box, double minZ, double maxZ);
    IBox3DM set(IBox2D box, int minZ, int maxZ);
    IBox3DM set(IBox2D box, double minZ, double maxZ);
    IBox3DM set(IBox2I box);
    IBox3DM set(IBox2D box);
    IBox3DM setZero();
    IBox3DM collapseStack();
    IBox3DM resetStack();
    IBox3DM pushBox();
    IBox3DM popBox();
    IBox3DM grow(double amount);
    IBox3DM grow(double x, double y, double z);
    IBox3DM grow(int amount);
    IBox3DM grow(int x, int y, int z);
    IBox3DM grow(IVec3I vec);
    IBox3DM grow(IVec3D vec);
    IBox3DM grow(IVec2I vec, int z);
    IBox3DM grow(IVec2I vec, double z);
    IBox3DM grow(IVec2D vec, int z);
    IBox3DM grow(IVec2D vec, double z);
    IBox3DM grow(IVec2I vec);
    IBox3DM grow(IVec2D vec);
    IBox3DM offset(int x, int y, int z);
    IBox3DM offset(double x, double y, double z);
    IBox3DM offset(IVec3I vec);
    IBox3DM offset(IVec3D vec);
    IBox3DM offset(IVec2I vec, int z);
    IBox3DM offset(IVec2I vec, double z);
    IBox3DM offset(IVec2D vec, int z);
    IBox3DM offset(IVec2D vec, double z);
    IBox3DM offset(IVec2I vec);
    IBox3DM offset(IVec2D vec);
    IBox3DM include(int x, int y, int z);
    IBox3DM include(double x, double y, double z);
    IBox3DM include(IVec3I vec);
    IBox3DM include(IVec3D vec);
    IBox3DM include(IVec2I vec, int z);
    IBox3DM include(IVec2I vec, double z);
    IBox3DM include(IVec2D vec, int z);
    IBox3DM include(IVec2D vec, double z);
    IBox3DM include(IVec2I vec);
    IBox3DM include(IVec2D vec);
    IBox3DM union(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3DM union(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3DM union(IVec3D boxFrom, IVec3D boxTo);
    IBox3DM union(IVec3I boxFrom, IVec3I boxTo);
    IBox3DM union(IBox3D box);
    IBox3DM union(IBox3I box);
    IBox3DM union(IBox2I box, int minZ, int maxZ);
    IBox3DM union(IBox2I box, double minZ, double maxZ);
    IBox3DM union(IBox2D box, int minZ, int maxZ);
    IBox3DM union(IBox2D box, double minZ, double maxZ);
    IBox3DM union(IBox2I box);
    IBox3DM union(IBox2D box);
    IBox3DM intersection(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3DM intersection(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3DM intersection(IVec3D boxFrom, IVec3D boxTo);
    IBox3DM intersection(IVec3I boxFrom, IVec3I boxTo);
    IBox3DM intersection(IBox3D box);
    IBox3DM intersection(IBox3I box);
    IBox3DM intersection(IBox2I box, int minZ, int maxZ);
    IBox3DM intersection(IBox2I box, double minZ, double maxZ);
    IBox3DM intersection(IBox2D box, int minZ, int maxZ);
    IBox3DM intersection(IBox2D box, double minZ, double maxZ);
    IBox3DM intersection(IBox2I box);
    IBox3DM intersection(IBox2D box);
    IBox3IM floor();
    IBox3IM round();
    IBox3IM ceil();
    IBox3DM copy();
}
