package com.artur114.bananalib.math.m3d.box;

import com.artur114.bananalib.math.core.m2d.box.IBox2DC;
import com.artur114.bananalib.math.core.m2d.box.IBox2IC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import org.jetbrains.annotations.Contract;

public interface IBox3IM extends IBox3I {
    IBox3IM set(int[] box);
    IBox3IM set(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3IM set(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3IM set(IVec3DC boxFrom, IVec3DC boxTo);
    IBox3IM set(IVec3IC boxFrom, IVec3IC boxTo);
    IBox3IM set(IBox3DC box);
    IBox3IM set(IBox3IC box);
    IBox3IM set(IBox2IC box, int minZ, int maxZ);
    IBox3IM set(IBox2IC box, double minZ, double maxZ);
    IBox3IM set(IBox2DC box, int minZ, int maxZ);
    IBox3IM set(IBox2DC box, double minZ, double maxZ);
    IBox3IM set(IBox2IC box);
    IBox3IM set(IBox2DC box);
    IBox3IM setZero();
    IBox3IM collapseStack();
    IBox3IM resetStack();
    IBox3IM pushBox();
    IBox3IM popBox();
    IBox3IM grow(double amount);
    IBox3IM grow(double x, double y, double z);
    IBox3IM grow(int amount);
    IBox3IM grow(int x, int y, int z);
    IBox3IM grow(IVec3IC vec);
    IBox3IM grow(IVec3DC vec);
    IBox3IM grow(IVec2IC vec, int z);
    IBox3IM grow(IVec2IC vec, double z);
    IBox3IM grow(IVec2DC vec, int z);
    IBox3IM grow(IVec2DC vec, double z);
    IBox3IM grow(IVec2IC vec);
    IBox3IM grow(IVec2DC vec);
    IBox3IM offset(int x, int y, int z);
    IBox3IM offset(double x, double y, double z);
    IBox3IM offset(IVec3IC vec);
    IBox3IM offset(IVec3DC vec);
    IBox3IM offset(IVec2IC vec, int z);
    IBox3IM offset(IVec2IC vec, double z);
    IBox3IM offset(IVec2DC vec, int z);
    IBox3IM offset(IVec2DC vec, double z);
    IBox3IM offset(IVec2IC vec);
    IBox3IM offset(IVec2DC vec);
    IBox3IM include(int x, int y, int z);
    IBox3IM include(double x, double y, double z);
    IBox3IM include(IVec3IC vec);
    IBox3IM include(IVec3DC vec);
    IBox3IM include(IVec2IC vec, int z);
    IBox3IM include(IVec2IC vec, double z);
    IBox3IM include(IVec2DC vec, int z);
    IBox3IM include(IVec2DC vec, double z);
    IBox3IM include(IVec2IC vec);
    IBox3IM include(IVec2DC vec);
    IBox3IM union(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3IM union(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3IM union(IVec3DC boxFrom, IVec3DC boxTo);
    IBox3IM union(IVec3IC boxFrom, IVec3IC boxTo);
    IBox3IM union(IBox3DC box);
    IBox3IM union(IBox3IC box);
    IBox3IM union(IBox2IC box, int minZ, int maxZ);
    IBox3IM union(IBox2IC box, double minZ, double maxZ);
    IBox3IM union(IBox2DC box, int minZ, int maxZ);
    IBox3IM union(IBox2DC box, double minZ, double maxZ);
    IBox3IM union(IBox2IC box);
    IBox3IM union(IBox2DC box);
    IBox3IM intersection(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3IM intersection(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3IM intersection(IVec3DC boxFrom, IVec3DC boxTo);
    IBox3IM intersection(IVec3IC boxFrom, IVec3IC boxTo);
    IBox3IM intersection(IBox3DC box);
    IBox3IM intersection(IBox3IC box);
    IBox3IM intersection(IBox2IC box, int minZ, int maxZ);
    IBox3IM intersection(IBox2IC box, double minZ, double maxZ);
    IBox3IM intersection(IBox2DC box, int minZ, int maxZ);
    IBox3IM intersection(IBox2DC box, double minZ, double maxZ);
    IBox3IM intersection(IBox2IC box);
    IBox3IM intersection(IBox2DC box);
    @Contract("-> this")
    IBox3IM toMutable();
    @Contract("-> new")
    IBox3I toImmutable();
    @Contract("-> new")
    IBox3DM toDouble();
    @Contract("-> new")
    IBox3IM copy();
}
