package com.artur114.bananalib.math.m3d.box;

import com.artur114.bananalib.math.core.m2d.box.IBox2DC;
import com.artur114.bananalib.math.core.m2d.box.IBox2IC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2DC;
import com.artur114.bananalib.math.core.m2d.vec.IVec2IC;
import com.artur114.bananalib.math.core.m3d.box.IBox3DC;
import com.artur114.bananalib.math.core.m3d.box.IBox3IC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3DC;
import com.artur114.bananalib.math.core.m3d.vec.IVec3IC;
import org.jetbrains.annotations.Contract;

public interface IBox3I extends IBox3IC {
    boolean contains(IBox3IC box);
    boolean contains(IBox3DC box);
    boolean contains(IVec3IC vec);
    boolean contains(IVec3DC vec);
    boolean contains(IVec2IC vec, int z);
    boolean contains(IVec2IC vec, double z);
    boolean contains(IVec2DC vec, int z);
    boolean contains(IVec2DC vec, double z);
    boolean contains(IVec2IC vec);
    boolean contains(IVec2DC vec);
    boolean contains(IBox2IC box, int minZ, int maxZ);
    boolean contains(IBox2IC box, double minZ, double maxZ);
    boolean contains(IBox2DC box, int minZ, int maxZ);
    boolean contains(IBox2DC box, double minZ, double maxZ);
    boolean contains(IBox2IC box);
    boolean contains(IBox2DC box);
    boolean intersects(IVec3DC boxFrom, IVec3DC boxTo);
    boolean intersects(IVec3IC boxFrom, IVec3IC boxTo);
    boolean intersects(IBox3DC box);
    boolean intersects(IBox3IC box);
    boolean intersects(IBox2IC box, int minZ, int maxZ);
    boolean intersects(IBox2IC box, double minZ, double maxZ);
    boolean intersects(IBox2DC box, int minZ, int maxZ);
    boolean intersects(IBox2DC box, double minZ, double maxZ);
    boolean intersects(IBox2IC box);
    boolean intersects(IBox2DC box);
    IBox3I grow(double amount);
    IBox3I grow(double x, double y, double z);
    IBox3I grow(int amount);
    IBox3I grow(int x, int y, int z);
    IBox3I grow(IVec3IC vec);
    IBox3I grow(IVec3DC vec);
    IBox3I grow(IVec2IC vec, int z);
    IBox3I grow(IVec2IC vec, double z);
    IBox3I grow(IVec2DC vec, int z);
    IBox3I grow(IVec2DC vec, double z);
    IBox3I grow(IVec2IC vec);
    IBox3I grow(IVec2DC vec);
    IBox3I offset(int x, int y, int z);
    IBox3I offset(double x, double y, double z);
    IBox3I offset(IVec3IC vec);
    IBox3I offset(IVec3DC vec);
    IBox3I offset(IVec2IC vec, int z);
    IBox3I offset(IVec2IC vec, double z);
    IBox3I offset(IVec2DC vec, int z);
    IBox3I offset(IVec2DC vec, double z);
    IBox3I offset(IVec2IC vec);
    IBox3I offset(IVec2DC vec);
    IBox3I include(int x, int y, int z);
    IBox3I include(double x, double y, double z);
    IBox3I include(IVec3IC vec);
    IBox3I include(IVec3DC vec);
    IBox3I include(IVec2IC vec, int z);
    IBox3I include(IVec2IC vec, double z);
    IBox3I include(IVec2DC vec, int z);
    IBox3I include(IVec2DC vec, double z);
    IBox3I include(IVec2IC vec);
    IBox3I include(IVec2DC vec);
    IBox3I union(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3I union(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3I union(IVec3DC boxFrom, IVec3DC boxTo);
    IBox3I union(IVec3IC boxFrom, IVec3IC boxTo);
    IBox3I union(IBox3DC box);
    IBox3I union(IBox3IC box);
    IBox3I union(IBox2IC box, int minZ, int maxZ);
    IBox3I union(IBox2IC box, double minZ, double maxZ);
    IBox3I union(IBox2DC box, int minZ, int maxZ);
    IBox3I union(IBox2DC box, double minZ, double maxZ);
    IBox3I union(IBox2IC box);
    IBox3I union(IBox2DC box);
    IBox3I intersection(int minX, int minY, int minZ, int maxX, int maxY, int maxZ);
    IBox3I intersection(double minX, double minY, double minZ, double maxX, double maxY, double maxZ);
    IBox3I intersection(IVec3DC boxFrom, IVec3DC boxTo);
    IBox3I intersection(IVec3IC boxFrom, IVec3IC boxTo);
    IBox3I intersection(IBox3DC box);
    IBox3I intersection(IBox3IC box);
    IBox3I intersection(IBox2IC box, int minZ, int maxZ);
    IBox3I intersection(IBox2IC box, double minZ, double maxZ);
    IBox3I intersection(IBox2DC box, int minZ, int maxZ);
    IBox3I intersection(IBox2DC box, double minZ, double maxZ);
    IBox3I intersection(IBox2IC box);
    IBox3I intersection(IBox2DC box);
    @Contract("-> new")
    IBox3IM toMutable();
    @Contract("-> this")
    IBox3I toImmutable();
    @Contract("-> new")
    IBox3D toDouble();
    @Contract("-> new")
    IBox3I copy();
}
